### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by ghost** [WrightonLabCSU/DRAM#101]
Hello,
We are facing error: "Failed to mmap memory dataSize=80676316565 File=DRAM_data/database_files/pfam.mmsmsa. Error 12." while preparing for database. 

It is halting with "subprocess.CalledProcessError: Command '['mmseqs', 'msa2profile', 'DRAM_data/database_files/pfam.mmsmsa', 'DRAM_data/database_files/pfam.mmspro', '--match-mode', '1', '--threads', '10']' returned non-zero exit status 1." 

Any suggestions to resolve it?

**Comment by shafferm** [comment]
Hi!

How much RAM is available on your system? It looks like there might not be enough RAM assigned to run this step.

Mike

**Comment by DirtyBlackOwl** [comment]
Hello!

Currently, we are using a system with 16GB. 
What is the minimum RAM requirement while skipping uniref90 and commercial KEGG?

Parth

**Comment by rmFlynn** [comment]
Unfortunately, even with skipping those databases, you may still need ~64GB for this step. You still have 2 options.
 
1. You can try using dram through [kbase](https://narrative.kbase.us/#catalog/apps/kb_DRAM/run_kb_dram_annotate/beta).
2. @shafferm has uploaded a minimum database set to [zenodo](https://zenodo.org/record/3827510), you can download the files and use `DRAM-setup.py set_database_locations` to skip this memory intensive step. However, there are problems with this approach, as detailed in this [issue thread](https://github.com/shafferm/DRAM/issues/30).

Good luck.

**Comment by DirtyBlackOwl** [comment]
@rmFlynn Thank you. The second option worked for us.
We are using DRAMv with the output of virsorter2, but it is giving an error given below: 

ValueError: No virsorter calls found in for-dramv/viral-affi-contigs-for-dramv.tab for scaffold V1_1_(paired)_contig_51-cat_1 from input fasta. 

If the viral-affi-contigs-for-dramv.tab file is skipped during annotation then it gives an auxiliary score error for the distill module.
Is there any way to solve this issue?

**Comment by rmFlynn** [comment]
In this cat the problem could be the "(", ")" characters. If you have not already, run  `DRAM-v.py remove_bad_characters -v tabfile.tab` and `clean_tabfile.tab and DRAM-v.py remove_bad_characters -i input_fasta.fa clean_input_fasta.fa` this may not remove the parens, so you may need to run your own command replacing "(" and ")" with "_". If running with the cleaned output does not work, then search for any matches in the viral-affi-contigs-for-dramv.tab that have the parens replaced, for example `grep "V1_1_.*paired.*_contig_51-cat_1" viral-affi-contigs-for-dramv.tab`. If there are no matches, then we need to figure out where that name went.

**Comment by rmFlynn** [comment]
Looks like this is solved
