### ISSUE TITLE
Error message saying fasta location returns no paths

### ISSUE THREAD

**Issue by dsgregoire** [WrightonLabCSU/DRAM#104]
Hello,

Prior to this, I have been able to use DRAm v 1.0 and 1.2 successfully with no issues. After downloading some genomes in .fa format and trying to run them through DRAM 1.2 today, I received the following error message:

`14 fastas found
2021-07-20 20:06:37.762165: Annotation started
Traceback (most recent call last):
  File "/opt/anaconda3/bin/DRAM.py", line 152, in <module>
    args.func(**args_dict)
  File "/opt/anaconda3/lib/python3.7/site-packages/mag_annotator/annotate_bins.py", line 969, in annotate_bins_cmd
    checkm_quality, rename_bins, keep_tmp_dir, low_mem_mode, threads, verbose)
  File "/opt/anaconda3/lib/python3.7/site-packages/mag_annotator/annotate_bins.py", line 999, in annotate_bins
    db_handler = DatabaseHandler(db_locs['description_db'])
  File "/opt/anaconda3/lib/python3.7/site-packages/mag_annotator/database_handler.py", line 17, in __init__
    raise ValueError('Database does not exist at path %s' % database_loc)
ValueError: Database does not exist at path None`

I haven't changed anything with respect to the DRAM installation run prior and I checked this with v 1.0 and 1.2 and still get the same error message. It seems to be registering the fasta files properly but stalls afterwards. I've also tried running it with just .fa files in the directory to make sure and still get the same thing.

Any help on this would be much appreciated.

**Comment by rmFlynn** [comment]
It looks like somehow dram is looking for a database that is not set in its config. The fastest way to inspect the config is with `DRAM-setup.py print_config`, take a look at the output and see if the text `Description db: ` is fallowed by a path, and that path exists. If you need to change the location of your databases, you can use DRAM-setup.py set_database_locations. More info on that sort of thing [here](https://github.com/shafferm/DRAM/wiki/5.-Managing,-updating-or-moving-a-DRAM-installation-and-databases).

Good luck, let us know how it goes.

**Comment by rmFlynn** [comment]
Hope it went well.

**Comment by karinevilleneuve** [comment]
Hi, I am getting the same error message. 
`DRAM-setup.py print_config` is giving me a path to `description_db.sqlite` and this path does exist. 
Any help on how to solve this would be greatly appreciated, thank you .
