### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by hannet91** [WrightonLabCSU/DRAM#106]
Hi, 

**I used the DRAM in conda environment with some errors. Can you tell me how to fix it, Thanks.**

$DRAM-v.py annotate -i /data/liaohp/project1/virus/Virsorter-SOP/all-final--viral-combined-derep.fa  -o annotation
2021-08-05 11:15:49.638597: Viral annotation started
0:00:00.944904: Retrieved database locations and descriptions
0:00:00.944963: Annotating NODE_27_length_79927_cov_6.839818||full
0:00:02.643946: Turning genes from prodigal to mmseqs2 db
/data/software/conda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py:739: UserWarning: No KEGG source provided so distillation will be of limited use.
  warnings.warn('No KEGG source provided so distillation will be of limited use.')
0:00:04.774285: Getting forward best hits from viral
0:00:05.556976: Getting reverse best hits from viral
0:00:06.177756: Getting descriptions of hits from viral
0:00:06.194178: Getting forward best hits from peptidase
0:00:07.080629: Getting reverse best hits from peptidase
0:00:07.776862: Getting descriptions of hits from peptidase
0:00:07.781495: Getting hits from pfam
0:00:16.991231: Getting hits from dbCAN
0:00:18.395969: Getting hits from VOGDB
/data/software/conda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py:42: UserWarning: No descriptions were found for your id's. Does this VOG02708 look like an id from vogdb_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
Traceback (most recent call last):
  File "/data/software/conda2/envs/DRAM/bin/DRAM-v.py", line 140, in <module>
    args.func(**args_dict)
  File "/data/software/conda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 403, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_locs_anno, db_handler, min_contig_size, prodigal_mode,
  File "/data/software/conda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 923, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/data/software/conda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 824, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/data/software/conda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 778, in annotate_orfs
    annotation_list.append(run_hmmscan_vogdb(gene_faa, db_locs['vogdb'], tmp_dir, threads, db_handler=db_handler,
  File "/data/software/conda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 343, in run_hmmscan_vogdb
    categories_str = description.split('; ')[-1]
AttributeError: 'NoneType' object has no attribute 'split'

**Here are the database in config.**

(DRAM) [liaohp@ubuntu DRAM-master] /data/software/DRAM-master
$DRAM-setup.py print_config
KEGG db: None
KOfam db: /data/software/DRAM-master/db-dramv/database_files/kofam_profiles.hmm
KOfam KO list: None
UniRef db: None
Pfam db: /data/software/DRAM-master/db-dramv/database_files/pfam.mmspro
Pfam hmm dat: /data/software/DRAM-master/db-dramv/Pfam-A.hmm.dat.gz
dbCAN db: /data/software/DRAM-master/db-dramv/database_files/dbCAN-HMMdb-V9.txt
dbCAN family activities: /data/software/DRAM-master/db-dramv/CAZyDB.07302020.fam-activities.txt
RefSeq Viral db: /data/software/DRAM-master/db-dramv/database_files/refseq_viral.20210804.mmsdb
MEROPS peptidase db: /data/software/DRAM-master/db-dramv/database_files/peptidases.20210804.mmsdb
VOGDB db: /data/software/DRAM-master/db-dramv/database_files/vog_latest_hmms.txt
VOG annotations: None
Description db: None
Genome summary form: /data/software/DRAM-master/db-dramv/database_files/genome_summary_form.20210804.tsv
Module step form: /data/software/DRAM-master/db-dramv/database_files/module_step_form.20210804.tsv
ETC module database: /data/software/DRAM-master/db-dramv/database_files/etc_mdoule_database.20210804.tsv
Function heatmap form: /data/software/DRAM-master/db-dramv/database_files/function_heatmap_form.20210804.tsv
AMG database: /data/software/DRAM-master/db-dramv/database_files/amg_database.20210804.tsv

**Comment by shafferm** [comment]
Hi @hannet91,

Sorry for the slow response. I have been off for a chunk of August and it has taken me a bit to catch up.

It looks like something failed during the set up of DRAM since you do not have the VOG annotations or description DB present in your config. Were any errors present when you set up DRAM?

Mike

**Comment by rmFlynn** [comment]
Hope this worked out!
