### ISSUE TITLE
[Feature Request]: prodigal train mode file argument

### ISSUE THREAD

**Issue by sixvable** [WrightonLabCSU/DRAM#110]
Hi, @shafferm 
Thanks for this wonderful tool! 
I found  that also there is a argument `--prodigal_mode train` in function `DRAM.py annotate`, it seems like there is no additional argument to supply a custom prodigal train files.

I am not good at python so I am afraid that I can not contribute a new PR. 😬

 sixvable

**Comment by shafferm** [comment]
Based on your pull request it looks like you can program in python pretty well!

I will look into this but at first glance it will take a bit of work to pull in training mode and then running gene calling with custom trained models in prodigal.

If you want to do this soon I think it might be easier to train with prodigal and run gene calling with prodigal using the custom model outside of DRAM. Then you can use DRAM on the `.faa` files that come out of that using `DRAM.py annotate_genes`. If you go this route I'd be really interested in the commands you use to do it as I have only every used the built in prodigal models.

Mike

**Comment by rmFlynn** [comment]
I don't expect to add this feature as the "annotate genes" feature already exists, allowing users to run prodigal however they see fit if the dram defaults don't work for them.
