### ISSUE TITLE
DRAM_setup.py error

### ISSUE THREAD

**Issue by TonyMane** [WrightonLabCSU/DRAM#115]
greetings, having some trouble setting up the databases required for DRAM. Trying this through an SGE submission queue. 
I've attached my submission (DRAM_setup.sh) and the output log (DRAM_setup.log). Any assistance would be valuable.
[DRAM_setup.sh.gz](https://github.com/shafferm/DRAM/files/7142024/DRAM_setup.sh.gz)
[DRAM_setup.log.gz](https://github.com/shafferm/DRAM/files/7142025/DRAM_setup.log.gz)

**Comment by rmFlynn** [comment]
Memory remains the biggest stumbling block to dram, but I will not be able to fix this today.
