### ISSUE TITLE
Parse genbank files to annotations.tsv

### ISSUE THREAD

**Issue by ellasiera** [WrightonLabCSU/DRAM#116]
DRAM got stuck at classification but all the GenBank files have been created. Is there a way to generate annotations.tsv without rerunning DRAM?
Also, looking at genes.faa, only KEGG and pfam were run. Does that mean I have to repeat the run?

**Comment by rmFlynn** [comment]
Sorry for the slow reply. Unfortunately, DRAM does not have the capability to continue an incomplete run at the moment. You will have to start over, but we may address this some day in the future.
Best of luck!
