### ISSUE TITLE
DataFrame is highly fragmented warning

### ISSUE THREAD

**Issue by smdabdoub** [WrightonLabCSU/DRAM#118]
Hi All,

I was running the MAG annotation process and got the following warning:

`0:09:51.057434: Getting reverse best hits from peptidase
DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py:120: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  hits[forward_hit] = [row.tId, rbh, row.seqIdentity, row.bitScore, row.eVal]
0:09:54.044486: Getting descriptions of hits from peptidase`

Doesn't seem to break anything, but might be worth looking into.

Thanks!
Shareef

**Comment by srisvs33** [comment]
Hello everyone, I have also got a similar warning message in my datasets. Do I need to be worried?

Many thanks
Venkat

**Comment by rmFlynn** [comment]
I do not think this is an immediate concern, but it is something we will try to fix in the future. Thank you for bringing it to our attention!
