### ISSUE TITLE
bitscore vs identity

### ISSUE THREAD

**Issue by slambrechts** [WrightonLabCSU/DRAM#130]
Hi,

I see that minimum bitScore of a search to retain hits is 60 by default. I am working with custom databases and I notice in the `annotations.tsv` file that hits with similar identity can produce widely different bitscores. e.g.: 

```
WP_023543351.1	WP_023543351.1 - Streptomyces niveus - [NiFe] Group 1h	        TRUE  	0.94	1156.0
WP_011516268.1	WP_011516268.1 - Cupriavidus metallidurans - [NiFe] Group 3d	FALSE	0.936	67.0

```

Is this purely due to the RBH being FALSE vs TRUE?

Before DRAM I searched for hits manually using diamond/mmseqs, and I used a minimum identity cutoff of 0.50 and query cover > 80%, but I'm not sure how that relates to the minimum bitScore used in DRAM?

**Comment by rmFlynn** [comment]
Sorry no one got to this last year, in short, bit score and evaluate both play a role is filtering hits in manners that are unique to each target database. Let me know which database in particular you are curious about, and I will try and fined an answer to the question if you are still searching for one.
