### ISSUE TITLE
Dram-V fails to merge large samples after running the annotate function

### ISSUE THREAD

**Issue by AJWing** [WrightonLabCSU/DRAM#139]
Good afternoon!

Recently, I've been trying to get ORFs and annotate a mix of metagenomes and viromes with dram-v...however, I've had mixed results. Out of 36 samples, 29 succeed in generating the proper annotation and genome summaries (annotate and distill) but 7 fail to finish. One issue is that the 7 that failed are anywhere from 5-10x larger in terms of the input file used compared to those that succeed. The 4 viromes have consistently timed out (would love to know how much memory and walltime you suggest for files ~100Mb) but something a little more strange has happened with the 3 samples that aren't viromes and are ~60Mb in size for the input files. Though it says the jobs pertaining to these 3 samples is COMPLETED successfully, it only shows vMAGs and the working directory folders in the samples directory. 

Here is the current code I use: 

<img width="1671" alt="Screen Shot 2022-01-24 at 4 43 40 PM" src="https://user-images.githubusercontent.com/29547481/150870961-8eb5d267-b90f-4659-a79f-1e85a80d1083.png">

and here is what the job status of the 3 samples look like in terms of memory and time efficiency:

![Screen Shot 2022-01-24 at 11 13 35 AM](https://user-images.githubusercontent.com/29547481/150871324-91ef9fda-5dcf-4393-8ec7-8c409489c557.png)

As of now, I've requested 1 node, 1 task per node, 1 cpu per task, 30gb mem per cpu, and 6.5 days to run.

Any and all help would be much appreciated! Let me know if there's any additional info I can provide and thanks.

**Comment by rmFlynn** [comment]
I would give at least 120gb for ram for the best chance of success. It is difficult to prescribe the exact amount of memory you will need, this is just an educated guess. Are you using CPUs with many cores, or is it 1 core you are using? The memory will depend on the number of cores.
