### ISSUE TITLE
DRAM prepare_database time? 

### ISSUE THREAD

**Issue by genesandatshirt** [WrightonLabCSU/DRAM#140]
I'm trying to finalize the installation of DRAM as it seems really useful to my research. I'm running the prepare_database step and can see it updating the description_db.sqlite file however it's been running 12 hrs and only reached 1.4 GB. I was told this file will end up at around 32 GB. At this pace, I will exceed a generous wall time of 8 days. My questions are: 

how are people getting this setup? 
Is there an alternative method or can I download a prepared_db for the most recent version rather than building it myself?
If this doesn't complete by day 8, would I have to start fresh? 

Any help getting this tool setup would be greatly appreciated! Thanks

Update: I've installed this locally instead without uniref.

**Comment by rmFlynn** [comment]
Let me know if the issue is not resolved. It is probably your environment. I have seen issues like this on servers with back up utilities, each wright triggers the utility and pauses the program.

**Comment by zburcham** [comment]
Hello, I am having a similar issue. My set up has been running for over 5 days and is only at 13 GB. The wall time on my server is only 7 days so I am not sure how I will be able to get this set up. Is there a way to speed up the setup process? I am currently using 29 threads.
