### ISSUE TITLE
Error: No descriptions were found for your id's when running DRAM-v.py annotate

### ISSUE THREAD

**Issue by ZongzhiWu** [WrightonLabCSU/DRAM#150]
Running Command:
`DRAM-v.py annotate -i k141_1725637_length_5527_cov_7.0013_B24__0_partial-cat_4.fasta -v $vs2/for-dramv/viral-affi-contigs-for-dramv.tab -o aaa --skip_trnascan --threads 28 --min_contig_size 1000`
Log and Error:
`2022-02-16 17:09:46.940236: Viral annotation started`
`0:00:31.667222: Retrieved database locations and descriptions`
`0:00:31.667359: Annotating k141_1725637_length_5527_cov_7.0013_B24__0_partial-cat_4`
`0:00:31.985086: Turning genes from prodigal to mmseqs2 db`
`0:00:34.442844: Getting hits from kofam`
`0:02:03.629720: Getting forward best hits from viral`
`0:02:07.453773: Getting reverse best hits from viral`
`0:02:09.531451: Getting descriptions of hits from viral`
`/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/database_handler.py:80: UserWarning: No descriptions were found for your id's. Does this NP_039597.1 look like an id from viral_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],`
`Traceback (most recent call last):`
  `File "/lustre/home/liutang/.conda/envs/dram/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)`
  `File "/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 473, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,`
  `File "/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1007, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,`
  `File "/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 915, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,`
  `File "/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 809, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_handler.db_locs['viral'], tmp_dir,`
  `File "/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 679, in do_blast_style_search
    hits = formater(hits, header_dict)`
  `File "/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 173, in get_basic_description
    header = header_dict[hit]`
`KeyError: 'NP_039597.1'`
Attempt for `DRAM-setup.py update_description_db`:
I also attempted to run `DRAM-setup.py update_description_db`, however this command was always killed by system after running for one hour. So how much RAM is needed for this command? And does this command require a network connection? How much time is needed for finishing this command?

**Comment by rmFlynn** [comment]
You must run `DRAM-setup.py update_description_db` it will take 1-6 hours depending on your system and number of dbs. It can take 32 to over 120 GB of ram.

**Comment by rmFlynn** [comment]
I will not need an internet connection.

**Comment by ZongzhiWu** [comment]
So what is the output file after finishing the command `DRAM-setup.py update_description_db`. How big is the output file? My local login node have 187 GB of RAM, why this command occupied all RAM and were killed by system in my local login node?

**Comment by ZongzhiWu** [comment]
I tried running the command again `DRAM-setup.py update_description_db`, and to my great disappointment, failed again. I wonder if there is a better solution...
![image](https://user-images.githubusercontent.com/73645801/154393138-1915d64a-ecc0-4aa7-ae57-af97878cbb69.png)

**Comment by ZongzhiWu** [comment]
My output file are only 13KB and 88KB for `description_db.sqlite-journal` and `description_db.sqlite`.
![image](https://user-images.githubusercontent.com/73645801/154442079-832ec481-7f72-4630-8c07-1230c0508bbf.png)
And It seems to need **512GB** of RAM in issue-26 https://github.com/WrightonLabCSU/DRAM/issues/26

**Comment by rmFlynn** [comment]
That person was experiencing an extreme problem, and it is probably the same for you. I will run it again and see if I can get a better idea. It should not use that much ram, in my experience. Does your server backup its disks?

**Comment by ZongzhiWu** [comment]
Thanks a lot!
It worked!
I allocated about 500GB of RAM for the command `DRAM-setup.py update_description_db`

**Comment by ZongzhiWu** [comment]
Sorry to bother @rmFlynn.
When I was running DRAM-v.py annoate, I come across a warning in `Getting hits from dbCAN` and an error in `Merging ORF annotations`.

DRAM-v.py annotate -i final-viral-combined-for-dramv.fa -v viral-affi-contigs-for-dramv.tab -o dramv-anno --skip_trnascan --threads 20 --min_contig_size 1000
2022-02-18 11:35:55.706231: Viral annotation started
0:00:00.069276: Retrieved database locations and descriptions
0:00:00.069419: Annotating final-viral-combined-for-dramv
0:00:00.168454: Turning genes from prodigal to mmseqs2 db
0:00:02.766406: Getting hits from kofam
0:01:15.732913: Getting forward best hits from viral
0:01:19.171040: Getting reverse best hits from viral
0:01:20.396248: Getting descriptions of hits from viral
0:01:20.584298: Getting forward best hits from peptidase
0:01:24.256477: Getting hits from pfam
0:09:35.575743: Getting hits from dbCAN
/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/annotate_bins.py:272: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  return pd.Series()
0:09:37.757511: Getting hits from VOGDB
0:10:28.305354: Merging ORF annotations
Traceback (most recent call last):
  File "/lustre/home/liutang/.conda/envs/dram/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 473, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1007, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 937, in annotate_fasta
    annotate_gff(gene_gff, renamed_gffs, annotations, prefix=prefix)
  File "/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 494, in annotate_gff
    annotations_to_add = {strip_endings(i, ['_id']): annotations.loc[old_gene_name, i]
  File "/lustre/home/liutang/.conda/envs/dram/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 495, in <dictcomp>
    for i in annotations.columns if i.endswith('_id')}
AttributeError: 'int' object has no attribute 'endswith'

**Comment by ZongzhiWu** [comment]
Oh, it will be very helpful!
Thank you very much for your great contribution to DRAM!!!

**Comment by rmFlynn** [comment]
FYI it looks like there is a problem in the bioconda update pipeline not related to dram. I think it will be fixed soon, but in the meantime you should be able to upgrade dram from git if not. You would activate the Conda environment and do something like `conda install pip` and then clone the git repo and `pip install ./` it may be slightly different. Sorry for the delay.

**Comment by ipetrushin** [comment]
Thanks for the advice about update_description. Running this task on 2Tb node, now it takes 350+ Gb for 11 hours

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1503663 ipetrus+  20   0  361.6g 360.9g  45736 S  17.8  35.8 174:23.49 DRAM-setup.py
```
I really doubt is good idea to store so much data in the SQLite database (25 Gb already and counting)
