### ISSUE TITLE
Issues while updating databases using DRAM-setup.py set_database_locations 

### ISSUE THREAD

**Issue by avishekdutta14** [WrightonLabCSU/DRAM#152]
Hi,

Thank you for this wonderful tool. 

I am facing an issue while updating description db using `DRAM-setup.py set_database_locations --update_description_db.`

After installing DRAM, everything was working fine except for a warning which said that a particular gene Id (database identifier) was missing from the description. I followed the solution (https://github.com/WrightonLabCSU/DRAM/issues/86), but the problem persisted. I felt that the database was not downloaded correctly. So, I removed the database and again prepared it using the following syntax:`DRAM-setup.py prepare_databases --output_dir DRAM_data --skip_uniref`. I also re-installed the DRAM-bio. Since the names 
during `DRAM-setup.py print_config` were not matching with the new database and the DRAM distillation forms, I updated the PATH using: `DRAM-setup.py set_database_locations`.

Everything looked fine except for KEGG db: and UniRef db: which was showing some database file names which were not present. I tried updating the description db using `DRAM-setup.py set_database_locations --update_description_db` but it returned error: No such file or directory: 'filename_h'. This error was related to the KEGG database. Since I did not have the KEGG database compiled for DRAM, I think I was receiving this error. Then I modified DRAM_CONFIG manually by replacing the filename for KEEG and UniRef with "None", and then imported the CONFIG, but still, the error persists: `FileNotFoundError: [Errno 2] No such file or directory: 'None_h'`.

I think that this error is due to the unavailability of the KEGG database. The same will be true for UniRef. I think that there is something that I am missing since I was able to run and update the description without KEGG and UniRef database before. Is there any location that I should use for `DRAM-setup.py set_database_locations --kegg_db_loc & --uniref_db_loc ` to let DRAM know that I am not using the KEGG and UniRef databases?

It will be really helpful if you can guide me with this.

Thanks in advance.

**Comment by rmFlynn** [comment]
The solution may be as simple at `DRAM-setup.py import_config --config_loc fix_me.txt ` then open fix_me.text find `"kofam": "<some path>/None_h"` and  `"uniref": "<some path>/None_h"` make them `"kofam": None` and  `"uniref": None` then save the file and import `DRAM-setup.py import_config --config_loc fix_me.txt` This is fully on me and I apologize.

**Comment by rmFlynn** [comment]
Let me know if you have problems after that, and I will address them!

**Comment by rmFlynn** [comment]
Sorry tipo in the commands above, when you use `DRAM-setup.py export_config --output_file fix_me.txt` what are the contents of the `fix_me.txt` file?

**Comment by avishekdutta14** [comment]
`{"kegg": None, "kofam": "/home/user/wmg_tools/annotation/DRAM_data/kofam_profiles.hmm", "kofam_ko_list": "/home/user/wmg_tools/annotation/DRAM_data/kofam_ko_list.tsv", "uniref": None, "pfam": "/home/user/wmg_tools/annotation/DRAM_data/pfam.mmspro", "dbcan": "/home/user/wmg_tools/annotation/DRAM_data/dbCAN-HMMdb-V10.txt", "viral": "/home/user/wmg_tools/annotation/DRAM_data/refseq_viral.20220221.mmsdb", "peptidase": "/home/user/wmg_tools/annotation/DRAM_data/peptidases.20220221.mmsdb", "vogdb": "/home/user/wmg_tools/annotation/DRAM_data/vog_latest_hmms.txt", "pfam_hmm_dat": "/home/user/wmg_tools/annotation/DRAM_data/Pfam-A.hmm.dat.gz", "dbcan_fam_activities": "/home/user/wmg_tools/annotation/DRAM_data/CAZyDB.07292021.fam-activities.txt", "vog_annotations": "/home/user/wmg_tools/annotation/DRAM_data/vog_annotations_latest.tsv.gz", "genome_summary_form": "/home/user/wmg_tools/annotation/DRAM_data/genome_summary_form.20220221.tsv", "module_step_form": "/home/user/wmg_tools/annotation/DRAM_data/module_step_form.20220221.tsv", "etc_module_database": "/home/user/wmg_tools/annotation/DRAM_data/etc_mdoule_database.20220221.tsv", "function_heatmap_form": "/home/user/wmg_tools/annotation/DRAM_data/function_heatmap_form.20220221.tsv", "amg_database": "/home/user/wmg_tools/annotation/DRAM_data/amg_database.20220221.tsv", "description_db": "/home/user/wmg_tools/annotation/DRAM_data/description_db.sqlite"}
`

**Comment by rmFlynn** [comment]
Try replacing it with this `{"kegg": null, "kofam": "/home/user/wmg_tools/annotation/DRAM_data/kofam_profiles.hmm", "kofam_ko_list": "/home/user/wmg_tools/annotation/DRAM_data/kofam_ko_list.tsv", "uniref": null, "pfam": "/home/user/wmg_tools/annotation/DRAM_data/pfam.mmspro", "dbcan": "/home/user/wmg_tools/annotation/DRAM_data/dbCAN-HMMdb-V10.txt", "viral": "/home/user/wmg_tools/annotation/DRAM_data/refseq_viral.20220221.mmsdb", "peptidase": "/home/user/wmg_tools/annotation/DRAM_data/peptidases.20220221.mmsdb", "vogdb": "/home/user/wmg_tools/annotation/DRAM_data/vog_latest_hmms.txt", "pfam_hmm_dat": "/home/user/wmg_tools/annotation/DRAM_data/Pfam-A.hmm.dat.gz", "dbcan_fam_activities": "/home/user/wmg_tools/annotation/DRAM_data/CAZyDB.07292021.fam-activities.txt", "vog_annotations": "/home/user/wmg_tools/annotation/DRAM_data/vog_annotations_latest.tsv.gz", "genome_summary_form": "/home/user/wmg_tools/annotation/DRAM_data/genome_summary_form.20220221.tsv", "module_step_form": "/home/user/wmg_tools/annotation/DRAM_data/module_step_form.20220221.tsv", "etc_module_database": "/home/user/wmg_tools/annotation/DRAM_data/etc_mdoule_database.20220221.tsv", "function_heatmap_form": "/home/user/wmg_tools/annotation/DRAM_data/function_heatmap_form.20220221.tsv", "amg_database": "/home/user/wmg_tools/annotation/DRAM_data/amg_database.20220221.tsv", "description_db": "/home/user/wmg_tools/annotation/DRAM_data/description_db.sqlite"} `

**Comment by rmFlynn** [comment]
It can't be `None` it must be `null`, it looks like a python dict, but it is not.

**Comment by avishekdutta14** [comment]
Thanks a lot! `null` worked. I am not getting any error for `DRAM-setup.py print_config` and `DRAM-setup.py set_database_locations --update_description_db`.

**Comment by avishekdutta14** [comment]
Another question, the primary reason for re-downloading and updating the database was the following warning

`/home/user/.local/lib/python3.6/site-packages/mag_annotator/database_handler.py:81: UserWarning: No descriptions were found for your id's. Does this GT2_Glyco_tranf_2_3 look like an id from dbcan_description
  db_name))
/home/user/.local/lib/python3.6/site-packages/mag_annotator/database_handler.py:81: UserWarning: No descriptions were found for your id's. Does this GT2_Glyco_tranf_2_4 look like an id from dbcan_description
  db_name))
`
This is still persisting. Is there a way to fix this?

**Comment by rmFlynn** [comment]
Ok that is actually a different problem that I only just now tracked down. dbCAN has changed its naming, and DRAM will need to catch up. I will put out a point release to fix this issue, unfortunately you can't fix it unless you want to hack the hmm and replace all instances of `GT2_*` with `GT2`. I think I can get the fix out in the next 24h.

**Comment by avishekdutta14** [comment]
Thanks a lot!

**Comment by icemduru** [comment]
I had the same problem. exporting the config file and fixing it with text editor solved the problem. thanks.

**Comment by icemduru** [comment]
Hi, 

I got the similar error:

UserWarning: No descriptions were found for your id's. Does this MER0232783 look like an id from peptidase_d
escription

**Comment by rmFlynn** [comment]
Well the solution as always is `DRAM-setup.py set_database_locations --update_description_db` sorry we missed this.

**Comment by rmFlynn** [comment]
I closed this because you can now specify the config file you want to use.

**Comment by Sneakypeat** [comment]
> Well the solution as always is `DRAM-setup.py set_database_locations --update_description_db` sorry we missed this.

Dear, can you help me with this I tried all the fixes, but I am getting a key error in pfam andthe  annotation gets terminated.

 Working on sample: V350296418_L04_UDB-160  (array job 38)
✔ Using bin directory: /home/201770173/New/dastool_results_v3/V350296418_L04_UDB-160/V350296418_L04_UDB-160_DASTool_bins
========================================
Sample:         V350296418_L04_UDB-160
Bin directory:  /home/201770173/New/dastool_results_v3/V350296418_L04_UDB-160/V350296418_L04_UDB-160_DASTool_bins
DRAM output:    /home/201770173/New/dram_camper_output/DRAM/V350296418_L04_UDB-160
CAMPER output:  /home/201770173/New/dram_camper_output/CAMPER/V350296418_L04_UDB-160
Distill output: /home/201770173/New/dram_camper_output/distill/V350296418_L04_UDB-160_distill.tsv
Started at:     Tue Jul 15 02:33:18 GST 2025
========================================
2025-07-15 02:33:21,810 - The log file is created at /home/201770173/New/dram_camper_output/DRAM/V350296418_L04_UDB-160/annotate.log.
2025-07-15 02:33:21,811 - 14 FASTAs found
2025-07-15 02:33:21,871 - Starting the Annotation of Bins with database configuration:


KOfam db:
    Citation: T. Aramaki, R. Blanc-Mathieu, H. Endo, K. Ohkubo, M. Kanehisa, S. Goto, and H. Ogata, "Kofamkoala: Kegg ortholog assignme$
KOfam KO list:
    Citation: T. Aramaki, R. Blanc-Mathieu, H. Endo, K. Ohkubo, M. Kanehisa, S. Goto, and H. Ogata, "Kofamkoala: Kegg ortholog assignme$
Pfam db:
    Citation: J. Mistry, S. Chuguransky, L. Williams, M. Qureshi, G. A. Salazar, E. L. Sonnhammer, S. C. Tosatto, L. Paladin, S. Raj, L$
    Description_Db_Updated: 07/15/2025, 00:29:59
dbCAN db:
    Citation: Y. Yin, X. Mao, J. Yang, X. Chen, F. Mao, and Y. Xu, "dbcan: a web resource for automated carbohydrate-active enzyme anno$
    Version: 11
    Description_Db_Updated: 07/15/2025, 00:27:03
MEROPS peptidase db:
    Description_Db_Updated: 07/15/2025, 00:27:02
    Citation: N. D. Rawlings, A. J. Barrett, P. D. Thomas, X. Huang, A. Bateman, and R. D. Finn, "The merops database of proteolytic en$

Pfam hmm dat:
    Description_Db_Updated: Unknown, or Never
    Citation: J. Mistry, S. Chuguransky, L. Williams, M. Qureshi, G. A. Salazar, E. L. Sonnhammer, S. C. Tosatto, L. Paladin, S. Raj, L$
dbCAN family activities:
    Citation: Y. Yin, X. Mao, J. Yang, X. Chen, F. Mao, and Y. Xu, "dbcan: a web resource for automated carbohydrate-active enzyme anno$
    Version: 11
    Upload_Date: 08062022
    Download Time: 07/14/2025, 12:30:53
    Origin: Downloaded by DRAM
dbCAN subfamily EC numbers:
    Citation: Y. Yin, X. Mao, J. Yang, X. Chen, F. Mao, and Y. Xu, "dbcan: a web resource for automated carbohydrate-active enzyme anno$
    Version: 11
    Upload_Date: 08062022
    Download Time: 07/14/2025, 12:30:56
    Origin: Downloaded by DRAM
VOG annotations:
    Description_Db_Updated: Unknown, or Never
    Citation: J. Thannesberger, H.-J. Hellinger, I. Klymiuk, M.-T. Kastner, F. J. Rieder, M. Schneider, S. Fister, T. Lion, K. Kosulin,$
    Version: latest
    Download Time: 07/14/2025, 12:30:59
    Origin: Downloaded by DRAM

Genome summary form:
    Branch: master
    Download Time: 07/14/2025, 12:31:00
    Origin: Downloaded by DRAM
Module step form:
    Branch: master
    Download Time: 07/14/2025, 12:31:01
    Origin: Downloaded by DRAM
ETC module database:
    Branch: master
    Download Time: 07/14/2025, 12:31:04
    Origin: Downloaded by DRAM
Function heatmap form:
    Branch: master
    Download Time: 07/14/2025, 12:31:02
    Origin: Downloaded by DRAM
AMG database:
    Branch: master
    Download Time: 07/14/2025, 12:31:03
    Origin: Downloaded by DRAM
2025-07-15 02:33:21,873 - Retrieved database locations and descriptions
2025-07-15 02:33:21,873 - Annotating bin.2.fa
2025-07-15 02:34:25,878 - Turning genes from prodigal to mmseqs2 db
2025-07-15 02:34:29,604 - Getting hits from kofam
2025-07-15 03:21:26,260 - One of your requested annotation databases is missing. If you did not specify KEGG database, distillate will $
2025-07-15 03:21:26,262 - Getting forward best hits from peptidase
2025-07-15 03:21:38,657 - Getting reverse best hits from peptidase
2025-07-15 03:21:42,128 - Getting descriptions of hits from peptidase
2025-07-15 03:21:42,275 - Getting hits from pfam
Traceback (most recent call last):
  File "/home/201770173/.conda/envs/DRAM/bin/DRAM.py", line 211, in <module>
    args.func(**args_dict)
  File "/home/201770173/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1531, in annotate_bins
    all_annotations = annotate_fastas(
  File "/home/201770173/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1410, in annotate_fastas
    annotate_fasta(
  File "/home/201770173/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1255, in annotate_fasta
    annotations = annotate_orfs(
  File "/home/201770173/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1107, in annotate_orfs
    run_mmseqs_profile_search(
  File "/home/201770173/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 268, in run_mmseqs_profile_$
    [
  File "/home/201770173/.conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 269, in <listcomp>
    "%s [%s]" % (pfam_descriptions[ascession], ascession)
KeyError: 'PF00773.24'
ERROR: DRAM annotation failed for V350296418_L04_UDB-160





Here is my config file:
{
  "search_databases": {
    "kegg": null,
    "kofam_hmm": "/home/201770173/DRAM_database/kofam_profiles.hmm",
    "kofam_ko_list": "/home/201770173/DRAM_database/kofam_ko_list.tsv",
    "uniref": null,
    "pfam": "/home/201770173/DRAM_database/pfam.mmspro",
    "dbcan": "/home/201770173/DRAM_database/dbCAN-HMMdb-V11.txt",
    "viral": "/home/201770173/DRAM_database/refseq_viral.20250714.mmsdb",
    "peptidase": "/home/201770173/DRAM_database/peptidases.20250714.mmsdb",
    "vogdb": "/home/201770173/DRAM_database/vog_latest_hmms.txt",
    "camper_hmm": null,
    "camper_fa_db": null,
    "camper_hmm_cutoffs": null,
    "camper_fa_db_cutoffs": null
  },
  "database_descriptions": {
    "pfam_hmm": "/home/201770173/DRAM_database/Pfam-A.hmm.dat.gz",
    "dbcan_fam_activities": "/home/201770173/DRAM_database/CAZyDB.08062022.fam-activities.txt",
    "dbcan_subfam_ec": "/home/201770173/DRAM_database/CAZyDB.08062022.fam.subfam.ec.txt",
    "vog_annotations": "/home/201770173/DRAM_database/vog_annotations_latest.tsv.gz"
  },
  "dram_sheets": {
    "camper_distillate": null,
    "genome_summary_form": "/home/201770173/DRAM_database/genome_summary_form.20250714.tsv",
    "module_step_form": "/home/201770173/DRAM_database/module_step_form.20250714.tsv",
    "etc_module_database": "/home/201770173/DRAM_database/etc_mdoule_database.20250714.tsv",
    "function_heatmap_form": "/home/201770173/DRAM_database/function_heatmap_form.20250714.tsv",
    "amg_database": "/home/201770173/DRAM_database/amg_database.20250714.tsv"
  },
  "dram_version": "1.5.0",
  "description_db": "/home/201770173/DRAM_database/description_db.sqlite",
  "setup_info": {
    "kofam_hmm": {
      "name": "KOfam db",
      "citation": "T. Aramaki, R. Blanc-Mathieu, H. Endo, K. Ohkubo, M. Kanehisa, S. Goto, and H. Ogata, \"Kofamkoala: Kegg ortholog ass$
    },
    "kofam_ko_list": {
      "name": "KOfam KO list",
      "citation": "T. Aramaki, R. Blanc-Mathieu, H. Endo, K. Ohkubo, M. Kanehisa, S. Goto, and H. Ogata, \"Kofamkoala: Kegg ortholog ass$
    },
    "pfam": {
      "name": "Pfam db",
      "citation": "J. Mistry, S. Chuguransky, L. Williams, M. Qureshi, G. A. Salazar, E. L. Sonnhammer, S. C. Tosatto, L. Paladin, S. Ra$
      "description_db_updated": "07/15/2025, 09:58:09"
    },
    "pfam_hmm": {
      "name": "Pfam hmm dat",
      "description_db_updated": "Unknown, or Never",
      "citation": "J. Mistry, S. Chuguransky, L. Williams, M. Qureshi, G. A. Salazar, E. L. Sonnhammer, S. C. Tosatto, L. Paladin, S. Ra$
    },
    "dbcan": {
      "name": "dbCAN db",
      "citation": "Y. Yin, X. Mao, J. Yang, X. Chen, F. Mao, and Y. Xu, \"dbcan: a web resource for automated carbohydrate-active enzyme$
      "version": "11",
      "description_db_updated": "07/15/2025, 00:27:03"
    },
    "viral": {
      "name": "RefSeq Viral db",
      "description_db_updated": "07/15/2025, 00:25:59",
      "citation": "J. R. Brister, D. Ako-Adjei, Y. Bao, and O. Blinkova, \"Ncbi viral genomes resource,\" Nucleic acids research, vol. 4$
      "viral_files": 1
    },
    "peptidase": {
      "name": "MEROPS peptidase db",
      "description_db_updated": "07/15/2025, 00:27:02",
      "citation": "N. D. Rawlings, A. J. Barrett, P. D. Thomas, X. Huang, A. Bateman, and R. D. Finn, \"The merops database of proteolyt$
    },
    "vogdb": {
      "name": "VOGDB db",
      "citation": "J. Thannesberger, H.-J. Hellinger, I. Klymiuk, M.-T. Kastner, F. J. Rieder, M. Schneider, S. Fister, T. Lion, K. Kosu$
      "version": "latest",
      "description_db_updated": "07/15/2025, 00:27:06"
    },
    "dbcan_fam_activities": {
      "name": "dbCAN family activities",
      "citation": "Y. Yin, X. Mao, J. Yang, X. Chen, F. Mao, and Y. Xu, \"dbcan: a web resource for automated carbohydrate-active enzyme$
      "version": "11",
      "upload_date": "08062022",
      "Download time": "07/14/2025, 12:30:53",
      "Origin": "Downloaded by DRAM"

 "name": "Pfam db",
      "citation": "J. Mistry, S. Chuguransky, L. Williams, M. Qureshi, G. A. Salazar, E. L. Sonnhammer, S. C. Tosatto, L. Paladin, S. R$
      "description_db_updated": "07/15/2025, 09:58:09"
    },
    "pfam_hmm": {
      "name": "Pfam hmm dat",
      "description_db_updated": "Unknown, or Never", _-> this might be the problem how to fix it._
      "citation": "J. Mistry, S. Chuguransky, L. Williams, M. Qureshi, G. A. Salazar, E. L. Sonnhammer, S. C. Tosatto, L. Paladin, S. R$
    },
    "dbcan": {
      "name": "dbCAN db",
      "citation": "Y. Yin, X. Mao, J. Yang, X. Chen, F. Mao, and Y. Xu, \"dbcan: a web resource for automated carbohydrate-active enzym$
      "version": "11",
      "description_db_updated": "07/15/2025, 00:27:03"
    },
    "viral": {
      "name": "RefSeq Viral db",
      "description_db_updated": "07/15/2025, 00:25:59",
      "citation": "J. R. Brister, D. Ako-Adjei, Y. Bao, and O. Blinkova, \"Ncbi viral genomes resource,\" Nucleic acids research, vol. $
      "viral_files": 1
    },
    "peptidase": {
      "name": "MEROPS peptidase db",
      "description_db_updated": "07/15/2025, 00:27:02",
      "citation": "N. D. Rawlings, A. J. Barrett, P. D. Thomas, X. Huang, A. Bateman, and R. D. Finn, \"The merops database of proteoly$
    },
    "vogdb": {
      "name": "VOGDB db",
      "citation": "J. Thannesberger, H.-J. Hellinger, I. Klymiuk, M.-T. Kastner, F. J. Rieder, M. Schneider, S. Fister, T. Lion, K. Kos$
      "version": "latest",
      "description_db_updated": "07/15/2025, 00:27:06"
    },
    "dbcan_fam_activities": {
      "name": "dbCAN family activities",
      "citation": "Y. Yin, X. Mao, J. Yang, X. Chen, F. Mao, and Y. Xu, \"dbcan: a web resource for automated carbohydrate-active enzym$
      "version": "11",
      "upload_date": "08062022",
      "Download time": "07/14/2025, 12:30:53",
      "Origin": "Downloaded by DRAM"
    },
    "dbcan_subfam_ec": {
      "name": "dbCAN subfamily EC numbers",
      "citation": "Y. Yin, X. Mao, J. Yang, X. Chen, F. Mao, and Y. Xu, \"dbcan: a web resource for automated carbohydrate-active enzym$
      "version": "11",
      "upload_date": "08062022",
      "Download time": "07/14/2025, 12:30:56",
      "Origin": "Downloaded by DRAM"
    },
    "vog_annotations": {
      "name": "VOG annotations",
      "description_db_updated": "Unknown, or Never",  _-> this might be the problem how to fix it._
      "citation": "J. Thannesberger, H.-J. Hellinger, I. Klymiuk, M.-T. Kastner, F. J. Rieder, M. Schneider, S. Fister, T. Lion, K. Kos$
      "version": "latest",
      "Download time": "07/14/2025, 12:30:59",
      "Origin": "Downloaded by DRAM"
    },
    "genome_summary_form": {
      "name": "Genome summary form",
      "branch": "master",
      "Download time": "07/14/2025, 12:31:00",
      "Origin": "Downloaded by DRAM"
    },
    "module_step_form": {
      "name": "Module step form",
      "branch": "master",
      "Download time": "07/14/2025, 12:31:01",
      "Origin": "Downloaded by DRAM"
    },
    "function_heatmap_form": {
      "name": "Function heatmap form",
      "branch": "master",
      "Download time": "07/14/2025, 12:31:02",
      "Origin": "Downloaded by DRAM"
    },
    "amg_database": {
      "name": "AMG database",
      "branch": "master",
      "Download time": "07/14/2025, 12:31:03",
      "Origin": "Downloaded by DRAM"
    },
"etc_module_database": {
      "name": "ETC module database",
      "branch": "master",
      "Download time": "07/14/2025, 12:31:04",
      "Origin": "Downloaded by DRAM"
    }
  },
  "log_path": null
}
