### ISSUE TITLE
How large should description_db.sqlite be?

### ISSUE THREAD

**Issue by y-hwang** [WrightonLabCSU/DRAM#155]
Hi! I want to get an understanding of how large description_db.sqlite is supposed to be because my set up is taking a long time. I have uniref set up but no kegg database. thanks!

**Comment by y-hwang** [comment]
Thanks for the suggestion, I guess I am wondering whether I am even close to being done and I want to compare the size of the file to estimate how long it would still take to run.

**Comment by ZongzhiWu** [comment]
I finished it on Feb 18 and the final size was ~30G @y-hwang

**Comment by rmFlynn** [comment]
Thanks! Sorry I did not get that info to you. Mine is only 24 gigs, I think. Thanks for contributing!

**Comment by diego00012138** [comment]
how large should it be without uniref and kegg
