### ISSUE TITLE
Download only dbs for DRAM-v?

### ISSUE THREAD

**Issue by michoug** [WrightonLabCSU/DRAM#159]
Hi,
I'm mainly interested with the virus part of your nice pipeline,
Would it be possible to add options to just setup DBs for this part specifically?
Best
Greg

**Comment by rmFlynn** [comment]
There would not be much of a reduction and this will be a feature in dram2 in the meantime the only way is to edit the dram source code. It would not require a lot of editing, mind you. Unfortunately, I don't have much time to work on it as of now.
