### ISSUE TITLE
Can i run DRAM in Workstation with 80Gb RAM and 32 threads?

### ISSUE THREAD

**Issue by kalonji08** [WrightonLabCSU/DRAM#161]
Hi Everyone !
I'm a novice and would like to find out if its worth trying to run DRAM with 80Gb of RAM and wanted to find out:
1 is it possible to NOT download the databases and run everything online
2 : if that's not an option, how can download all the required databases?
Thanks for the help

**Comment by rmFlynn** [comment]
If you run it in low-mem mode and don't use all your threads, it may work. If you can run the setup script, then you should be able to annotate your datasets.

**Comment by kalonji08** [comment]
@rmFlynn Thank you very much. I will give it a try

**Comment by rmFlynn** [comment]
Sorry, I did not fully answer your question. 
1.  You do need to download the database, in some way
2.  There is a secrete pre-made database  here: https://zenodo.org/record/3827510 it is smaller, and should be faster, but it is way out of date. Also, I can't promise it will work. 
Good luck

**Comment by kalonji08** [comment]
@rmFlynn Thank you so much this should help, I hope it works too :)
