### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Pengfei-Turbo** [WrightonLabCSU/DRAM#163]
Hi，I have downloaded the database and when I do the annotation it reports the following error：
Traceback (most recent call last):
  File "/share/data1/private/youfen.qian/software/miniconda3/envs/Compare/bin/DRAM-v.py", line 5, in <module>
    from mag_annotator.annotate_vgfs import annotate_vgfs, remove_bad_chars
  File "/share/data1/private/youfen.qian/software/miniconda3/envs/Compare/lib/python3.7/site-packages/mag_annotator/annotate_vgfs.py", line 12, in <module>
    from mag_annotator.annotate_bins import annotate_fastas
  File "/share/data1/private/youfen.qian/software/miniconda3/envs/Compare/lib/python3.7/site-packages/mag_annotator/annotate_bins.py", line 283
    if len(y := re.findall('^[A-Z]*[0-9]*', str(x))[0]) > 0], 
             ^
SyntaxError: invalid syntax
Python version: 3.7

Database：Processed search databases
KEGG db: None
KOfam db: DRAM_data/kofam_profiles.hmm
KOfam KO list: DRAM_data/kofam_ko_list.tsv
UniRef db: DRAM_data/uniref90.20220323.mmsdb
Pfam db: DRAM_data/pfam.mmspro
dbCAN db: DRAM_data/dbCAN-HMMdb-V10.txt
RefSeq Viral db: DRAM_data/refseq_viral.20220323.mmsdb
MEROPS peptidase db: DRAM_data/peptidases.20220323.mmsdb
VOGDB db: DRAM_data/vog_latest_hmms.txt

Descriptions of search database entries
Pfam hmm dat: DRAM_data/Pfam-A.hmm.dat.gz
dbCAN family activities: DRAM_data/CAZyDB.07292021.fam-activities.txt
VOG annotations: DRAM_data/vog_annotations_latest.tsv.gz

Description db: DRAM_data/description_db.sqlite

DRAM distillation sheets
Genome summary form: DRAM_data/genome_summary_form.20220323.tsv
Module step form: DRAM_data/module_step_form.20220323.tsv
ETC module database: DRAM_data/etc_mdoule_database.20220323.tsv
Function heatmap form: DRAM_data/function_heatmap_form.20220323.tsv
AMG database: DRAM_data/amg_database.20220323.tsv

Please give me some suggestion, Thanks a lot!

**Comment by rmFlynn** [comment]
I see now the problem is I forgot myself and used an assignment expression . I will fix this Monday, but for now if you want you can upgrade python to 3.8 and it will fix the problem.

**Comment by Pengfei-Turbo** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi Dr. Rory,
           My program is ready to work, after I create a separate environment. The problem may be due to the incompatibility of my previous environment, Thanks for your reply.  Best wishes,  Turbo.
    
        
            
        
    
    
        
        

        
    

    On 3/24/2022 22:03，Rory M ***@***.***> wrote： 



Looks like a bug to me. If you can share the input with me, maybe I can track it down faster. I will need to fix this somehow. Thanks for finding this! I will test on 3.7, but it should be fine.
