### ISSUE TITLE
vMAG column clarification

### ISSUE THREAD

**Issue by LeoBusse** [WrightonLabCSU/DRAM#164]
Hello,

Thank you for developing this great tool!

I was just looking through the file outputs of the distill step, and was curious what the "Viral genes with host benefits" column refers to in the vMAG_stats.tsv file. Do these genes of viral origin and not bacterial origin, so not considered AMGs, influence host metabolism? 

Thank you!
Leora

**Comment by rmFlynn** [comment]
I did not code this part of DRAM my self. I believe this is a label provided by VOGdb and not modified directly by the DRAM process its self. I don't trust VOGdb completely on its own, but you may find this information useful in context. This supplementary file may provide more insight into vMAG_stats.tsv
[SOM_SUBMIT_NAR_flat_with_reviewcomments_FINAL06292020.pdf](https://github.com/WrightonLabCSU/DRAM/files/8382791/SOM_SUBMIT_NAR_flat_with_reviewcomments_FINAL06292020.pdf)
.

**Comment by LeoBusse** [comment]
Thank you so much!
