### ISSUE TITLE
dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by SilasK** [WrightonLabCSU/DRAM#168]
We encountered this error in dram. Do you have any idea? https://github.com/metagenome-atlas/atlas/issues/506

`dlopen: cannot load any more object with static TLS``

With dram v1.2

**Comment by rmFlynn** [comment]
This is an interesting project, I want the next generation of DRAM to integrate with snakemake more and I have worked with dram in Snakemake often as of late, but never seen this error. My first reaction is that it has nothing to do with dram dlopen relates to dynamic shared objects in Linux, so this could be anything, but I would think that it is a snakemake looking error. I will look more if you still have the problem in the coming days. Good luck!

**Comment by rmFlynn** [comment]
If you make a Snakemake module for DRAM that would be awesome, and you would get credit in one that the lab would officially ship and support! DRAM 2 should work more with Snakemake and if I can, I would be willing to pull you into DRAM2 in that area, and that would mean publication credit, so stay posted in a month or 2 if that is interesting to you.

**Comment by SilasK** [comment]
I would love to contribute to DRAM2. I have some suggestions. Tell me where I should write them down.

**Comment by bcpd** [comment]
A quick comment: the error persists if I install DRAM outside of ATLAS. Running `DRAM.py annotate` results in:

```
Traceback (most recent call last):
  File "/home/mixtures/miniconda3/envs/DRAM/bin/DRAM.py", line 5, in <module>
    from mag_annotator.annotate_bins import annotate_bins_cmd, annotate_called_genes_cmd, merge_annotations_cmd
  File "/home/mixtures/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 9, in <module>
    from skbio.io import read as read_sequence
  File "/home/mixtures/miniconda3/envs/DRAM/lib/python3.10/site-packages/skbio/__init__.py", line 19, in <module>
    import skbio.diversity  # noqa
  File "/home/mixtures/miniconda3/envs/DRAM/lib/python3.10/site-packages/skbio/diversity/__init__.py", line 402, in <module>
    from ._driver import (alpha_diversity, beta_diversity, partial_beta_diversity,
  File "/home/mixtures/miniconda3/envs/DRAM/lib/python3.10/site-packages/skbio/diversity/_driver.py", line 13, in <module>
    import sklearn.metrics
  File "/home/mixtures/miniconda3/envs/DRAM/lib/python3.10/site-packages/sklearn/__init__.py", line 83, in <module>
    from .utils._show_versions import show_versions
  File "/home/mixtures/miniconda3/envs/DRAM/lib/python3.10/site-packages/sklearn/utils/_show_versions.py", line 12, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: dlopen: cannot load any more object with static TLS
```

Help greatly appreciated!

**Comment by rmFlynn** [comment]
Fascinating

**Comment by rmFlynn** [comment]
I wish I could emulate the error but I don't have much time. Do you think you can create an environment where this line will not run with the same error? `from skbio.io import read as read_sequence` perhaps you can run that command outside of DRAM, but inside the environment in which DRAM Will not run. Obvious question is have you contacted scykit-bio about this problem

**Comment by rmFlynn** [comment]
> I would love to contribute to DRAM2. I have some suggestions. Tell me where I should write them down.

Sorry, I got side tracked. There is now a place in discussion for folks to talk about new features. I want to open that up to more stuff some day, but for now this is the only topic. Thanks for your patience!

**Comment by SilasK** [comment]
> > I would love to contribute to DRAM2. I have some suggestions. Tell me where I should write them down.
> 
> Sorry, I got side tracked. There is now a place in discussion for folks to talk about new features. I want to open that up to more stuff some day, but for now this is the only topic. Thanks for your patience!

Can you give me the link to it?

**Comment by rmFlynn** [comment]
> > > I would love to contribute to DRAM2. I have some suggestions. Tell me where I should write them down.
> > 
> > 
> > Sorry, I got side tracked. There is now a place in discussion for folks to talk about new features. I want to open that up to more stuff some day, but for now this is the only topic. Thanks for your patience!
> 
> Can you give me the link to it?
[The Future of DRAM ](https://github.com/WrightonLabCSU/DRAM/discussions/172) You will be the first to post, thanks!!
