### ISSUE TITLE
DRAM-setup.py doesn't work

### ISSUE THREAD

**Issue by ExaptedAI** [WrightonLabCSU/DRAM#170]
Cloned from git and everything worked until the following snag...

![image](https://user-images.githubusercontent.com/92825206/162476775-af37dab3-3ea7-4588-a876-cd6d2f50b9b0.png)

**Comment by rmFlynn** [comment]
I don't advise setting up dram without conda, and without using the bioconda package. It looks like scipy is not installed or the wrong version.
