### ISSUE TITLE
No descriptions were found for your id's

### ISSUE THREAD

**Issue by fanlu-f** [WrightonLabCSU/DRAM#173]
Hi:

There is an error when I run the DRAM(1.3.5). I can got output file, but there are some warnning on running. How can I solve the problem?

My command:
DRAM-v.py annotate -i Virsorter/prep-for-dramv/for-dramv/final-viral-combined-for-dramv.fa -v Virsorter/prep-for-dramv/for-dramv/viral-affi-contigs-for-dramv.tab -o DRAM/annotation --threads 80

2022-04-25 15:28:51.408952: Viral annotation started
0:00:00.658180: Retrieved database locations and descriptions
0:00:00.658404: Annotating final-viral-combined-for-dramv
0:03:27.949603: Turning genes from prodigal to mmseqs2 db
0:03:32.461027: Getting hits from kofam
1:07:27.587434: Getting forward best hits from viral
1:07:43.279157: Getting reverse best hits from viral
1:07:46.576263: Getting descriptions of hits from viral
1:07:46.917444: Getting forward best hits from peptidase
1:08:00.528259: Getting reverse best hits from peptidase
1:08:01.724895: Getting descriptions of hits from peptidase
1:08:01.751744: Getting hits from pfam
1:08:12.406818: Getting hits from dbCAN
/home/iwtr/anaconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_handler.py:81: UserWarning: No descriptions were found for your id's. Does this SLH look like an id from dbcan_description
  warnings.warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
1:09:35.688055: Getting hits from VOGDB
2:02:41.884778: Merging ORF annotations
2:33:03.795533: Annotations complete, processing annotations
2:33:04.161128: Annotations complete, assigning auxiliary scores and flags
/home/iwtr/anaconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py:184: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  virsorter_genes['start_position'] = virsorter_genes['start_position'].astype(int)
/home/iwtr/anaconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py:185: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  virsorter_genes['end_position'] = virsorter_genes['end_position'].astype(int)
2:34:20.184542: Completed annotations

The database:
Processed search databases
KEGG db: None
KOfam db: /home/iwtr/Microbiome/FL/DRAM_data/kofam_profiles.hmm
KOfam KO list: /home/iwtr/Microbiome/FL/DRAM_data/kofam_ko_list.tsv
UniRef db: /home/iwtr/Microbiome/FL/DRAM_data/uniref90.20220423.mmsdb
Pfam db: /home/iwtr/Microbiome/FL/DRAM_data/pfam.mmspro
dbCAN db: /home/iwtr/Microbiome/FL/DRAM_data/dbCAN-HMMdb-V10.txt
RefSeq Viral db: /home/iwtr/Microbiome/FL/DRAM_data/refseq_viral.20220424.mmsdb
MEROPS peptidase db: /home/iwtr/Microbiome/FL/DRAM_data/peptidases.20220424.mmsdb
VOGDB db: /home/iwtr/Microbiome/FL/DRAM_data/vog_latest_hmms.txt

Descriptions of search database entries
Pfam hmm dat: /home/iwtr/Microbiome/FL/DRAM_data/Pfam-A.hmm.dat.gz
dbCAN family activities: /home/iwtr/Microbiome/FL/DRAM_data/CAZyDB.07292021.fam-activities.txt
VOG annotations: /home/iwtr/Microbiome/FL/DRAM_data/vog_annotations_latest.tsv.gz

Description db: /home/iwtr/Microbiome/FL/DRAM_data/description_db.sqlite

DRAM distillation sheets
Genome summary form: /home/iwtr/Microbiome/FL/DRAM_data/genome_summary_form.20220424.tsv
Module step form: /home/iwtr/Microbiome/FL/DRAM_data/module_step_form.20220424.tsv
ETC module database: /home/iwtr/Microbiome/FL/DRAM_data/etc_mdoule_database.20220424.tsv
Function heatmap form: /home/iwtr/Microbiome/FL/DRAM_data/function_heatmap_form.20220424.tsv
AMG database: /home/iwtr/Microbiome/FL/DRAM_data/amg_database.20220424.tsv

**Comment by rmFlynn** [comment]
This is a warning, not an error. Sometimes dbCAN has an ID but no descriptions. The nature of this warning is a bit more complex because it is only raised when no dbCAN descriptions are found for a set of dbCAN IDs. In this case, the output is either cut off, or no IDs were found, and an empty set was past. We are working to resolve this ambiguity, and I will check that this warning is not triggered by an empty set. However, for the time being, it seems that the program is working as intended. Were there dbCAN IDs you expected to find in the output? Or some other anomalie?

**Comment by rmFlynn** [comment]
Let me know if this issue continues to impact your work. Thanks!
