### ISSUE TITLE
ID from viral_description error (database_handler.py) with no output

### ISSUE THREAD

**Issue by callaband** [WrightonLabCSU/DRAM#174]
Following [this protocol](https://dx.doi.org/10.17504/protocols.io.bwm5pc86) to extract and annotate phage in several hundred genomes: VirSorter2 (v2.2.3) --> checkV(db-v1.1) --> VirSorter2 --> DRAMv(v1.3.5). 
DRAM is set up in its own conda environment on a remote server (linux).
VirSorter2 outputs with no errors.
The DRAMv command below results in basically no output - working directory only, no .tsv files. It has a very similar error/failure for all test files (3 chosen at random) from my dataset. 

Set-up:
Processed search databases
KEGG db: None
KOfam db: /panfs/user/DRAM_databases/kofam_profiles.hmm
KOfam KO list: /panfs/user/DRAM_databases/kofam_ko_list.tsv
UniRef db: /panfs/user/DRAM_databases/uniref90.20220422.mmsdb
Pfam db: /panfs/user/DRAM_databases/pfam.mmspro
dbCAN db: /panfs/user/DRAM_databases/dbCAN-HMMdb-V10.txt
RefSeq Viral db: /panfs/user/DRAM_databases/refseq_viral.20220422.mmsdb
MEROPS peptidase db: /panfs/user/DRAM_databases/peptidases.20220422.mmsdb
VOGDB db: /panfs/user/DRAM_databases/vog_latest_hmms.txt

Descriptions of search database entries
Pfam hmm dat: /panfs/user/DRAM_databases/Pfam-A.hmm.dat.gz
dbCAN family activities: /panfs/user/DRAM_databases/CAZyDB.07292021.fam-activities.txt
VOG annotations: /panfs/user/DRAM_databases/vog_annotations_latest.tsv.gz

Description db: /panfs/user/DRAM_databases/description_db.sqlite

DRAM distillation sheets
Genome summary form: /panfs/user/DRAM_databases/genome_summary_form.20220422.tsv
Module step form: /panfs/user/DRAM_databases/module_step_form.20220422.tsv
ETC module database: /panfs/user/DRAM_databases/etc_mdoule_database.20220422.tsv
Function heatmap form: /panfs/user/DRAM_databases/function_heatmap_form.20220422.tsv
AMG database: /panfs/user/DRAM_databases/amg_database.20220422.tsv

```
(DRAMv) -bash-4.2$ DRAM-v.py annotate -i vs2-pass2/Sample/for-dramv/final-viral-combined-for-dramv.fa -v vs2-pass2/Sample/for-dramv/viral-affi-contigs-for-dramv.tab -o DRAMv/Sample --skip_trnascan --threads 32 --min_contig_size 1000
2022-05-02 00:28:54.979935: Viral annotation started
0:00:00.029301: Retrieved database locations and descriptions
0:00:00.029340: Annotating final-viral-combined-for-dramv
0:00:00.949880: Turning genes from prodigal to mmseqs2 db
0:00:03.983812: Getting hits from kofam
0:03:03.337192: Getting forward best hits from viral
0:03:10.642982: Getting reverse best hits from viral
0:03:13.274047: Getting descriptions of hits from viral
/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/database_handler.py:81: UserWarning: No descriptions were found for your id's. Does this YP_007348955.1 look like an id from viral_description
  warnings.warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/DRAMv/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 475, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1013, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 921, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 814, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_handler.db_locs['viral'], tmp_dir,
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 684, in do_blast_style_search
    hits = formater(hits, header_dict)
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 173, in get_basic_description
    header = header_dict[hit]
KeyError: 'YP_007348955.1'
```
I think there is potentially some incongruity between reference database files - maybe the sequence DB is newer than the annotation database?

**Comment by ipetrushin** [comment]
I got the same error, described in #167 and #150
How large is your SQLite database?

**Comment by rmFlynn** [comment]
Have you run `DRAM-setup.py --update_description_db`? This may solve the problem. If not, I will need to investigate.

**Comment by callaband** [comment]
DRAM-setup.py --update_description_db [Error that it doesn't exist]
DRAM-setup.py update_description_db [Killed - out of memory]
DRAM-setup.py update_description_db [allotted 32 threads, 100GB, 24hrs]
`/var/spool/slurmd/job250223/slurm_script: line 16:  6483 Killed                  DRAM-setup.py update_description_db
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=250223.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.`

DRAM-setup.py update_description_db [allotted 64 threads, 500GB, 24hrs] - ended at time limit, no errors, no done signal

Rerun of original code: 
`(DRAMv) -bash-4.2$ DRAM-v.py annotate -i vs2-pass2/Sample/for-dramv/final-viral-combined-for-dramv.fa -v vs2-pass2/Sample/for-dramv/viral-affi-contigs-for-dramv.tab -o DRAMv/Sample --skip_trnascan --threads 16 --min_contig_size 1000
2022-05-05 09:38:07.484330: Viral annotation started
0:00:00.019702: Retrieved database locations and descriptions
0:00:00.019757: Annotating final-viral-combined-for-dramv
0:00:00.992726: Turning genes from prodigal to mmseqs2 db
0:00:04.122259: Getting hits from kofam
0:02:36.207840: Getting forward best hits from viral
0:02:43.669042: Getting reverse best hits from viral
0:02:45.590660: Getting descriptions of hits from viral
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/DRAMv/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 475, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1013, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 921, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 814, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_handler.db_locs['viral'], tmp_dir,
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 681, in do_blast_style_search
    header_dict = db_handler.get_descriptions(hits['%s_hit' % db_name], '%s_description' % db_name)
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/database_handler.py", line 75, in get_descriptions
    descriptions = [
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/mag_annotator/database_handler.py", line 78, in <listcomp>
    for des in self.session.query(description_class).filter(description_class.id.in_(chunk)).all() 
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2768, in all
    return self._iter().all()
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/user/miniconda3/envs/DRAMv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT viral_description.id AS viral_description_id, viral_description.description AS viral_description_description 
FROM viral_description 
WHERE viral_description.id IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('YP_009909514.1', 'YP_009909551.1', 'YP_001700679.1', 'YP_009909512.1', 'YP_009909547.1', 'YP_001700676.1', 'YP_009909506.1', 'YP_009909503.1', 'YP_001700612.1', 'YP_009909544.1', 'YP_001700610.1', 'YP_009909548.1', 'YP_001700606.1', 'YP_009909538.1', 'YP_009909502.1', 'YP_009909723.1', 'YP_009909555.1', 'YP_001700607.1', 'YP_010065090.1', 'YP_009909553.1', 'YP_009909726.1', 'YP_009909546.1', 'YP_001700645.1', 'YP_001700675.1', 'YP_001700682.1', 'YP_001700606.1', 'YP_004957457.1', 'YP_009877438.1', 'YP_001700569.1', 'YP_001700607.1', 'YP_009909525.1', 'NP_945047.1', 'YP_001700608.1', 'YP_001700611.1', 'YP_009818322.1', 'YP_001700565.1', 'YP_001700574.1', 'YP_001700610.1', 'YP_009909721.1', 'YP_001700613.1', 'YP_009909717.1', 'YP_009909560.1', 'YP_001700612.1', 'YP_009909720.1', 'YP_009855362.1', 'YP_009999982.1', 'YP_001700609.1', 'YP_007003042.1', 'YP_009909493.1', 'YP_001700611.1', 'YP_009909754.1', 'YP_001700613.1', 'YP_009909502.1', 'YP_009909720.1', 'YP_009909752.1', 'YP_007348955.1', 'YP_009909559.1', 'YP_009196813.1', 'YP_009909562.1', 'YP_009909515.1', 'YP_009909505.1', 'YP_001700608.1', 'YP_001700607.1', 'YP_009909760.1', 'YP_009909725.1', 'YP_009909545.1', 'YP_009909503.1', 'YP_001700549.1', 'YP_001700674.1', 'YP_009909724.1', 'YP_009909717.1', 'YP_009152022.1', 'YP_010052991.1', 'YP_010078711.1', 'YP_009909740.1', 'YP_009909504.1', 'YP_010091605.1', 'YP_001700621.1', 'YP_001700566.1', 'YP_004934532.1', 'YP_001700644.1', 'YP_009909722.1', 'YP_001700609.1', 'YP_009877363.1', 'YP_009043891.1', 'YP_009909516.1', 'YP_009909554.1', 'YP_009909513.1', 'YP_009909549.1', 'NP_945045.1', 'YP_009909561.1', 'YP_009909728.1', 'NP_945050.1', 'YP_001700568.1')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)`

It didn't seem to help. Other ideas?

**Comment by rmFlynn** [comment]
If I'm understanding everything correctly it looks like when you're database build timed out it left the SQL database locked. I suggest you use print config to find the SQL file and delete it. Unfortunately at this time it is very difficult to use dram without the SQL database being built. I can discuss with some of the other metabolism people whether or not it would be possible to create an option to not use the database but that's not going to help you now. I highly suggest you create a job that can run for several days as it is seems that your HPC is using a slow form of hard disk storage which is getting in the way of building the database and will undoubtedly slow your runtime. FYI, because IO is the bottleneck increasing the number of CPUs is unlikely to help, only increasing memory. I apologize that building the data base is necessary we are looking at hosting options as well as alternative memory map systems.

**Comment by rmFlynn** [comment]
Glad to hear it, That warning is from using older pandas technics and should not affect your code. We will be trying to fix it, though. I am sorry that the setup process is such a pain generally. This is also something we are working on, thanks for baring with us. Good luck with your science!

**Comment by callaband** [comment]
Thank you so much for your prompt assistance!

**Comment by maocheng2020** [comment]
I'm getting a similar error when I annotate my MAGs. Can you please tell me what happened? How should I fix these warnings？Thank you so much!
@rmFlynn  @callaband 

2022-05-28 03:49:47.216692: Annotation started
0:00:00.011804: Retrieved database locations and descriptions
0:00:00.011871: Annotating juneG_2_idba_200_metabat_genomes.56
0:00:23.626260: Turning genes from prodigal to mmseqs2 db
0:00:26.075080: Getting hits from kofam
0:23:39.890580: Getting forward best hits from peptidase
0:23:56.350963: Getting reverse best hits from peptidase
0:24:00.142106: Getting descriptions of hits from peptidase
0:24:01.450417: Getting hits from pfam
0:24:30.187237: Getting hits from dbCAN
/home/pc/data2/software/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_handler.py:81: UserWarning: No descriptions were found for your id's. Does this SLH look like an id from dbcan_description
  warnings.warn("**No descriptions were found for your id's.** Does this %s look like an id from %s" % (list(ids)[0],
0:24:50.441015: Merging ORF annotations
/home/pc/data2/software/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py:603: UserWarning: No rRNAs were detected, no rrnas.tsv file will be created.
  warnings.warn('**No rRNAs were detected, no rrnas.tsv file will be created.**')
0:26:13.866332: Annotations complete, processing annotations
0:26:14.033130: Completed annotations

 DRAM-setup.py version
1.3.5
DRAM-setup.py print_config
Processed search databases
KEGG db: None
KOfam db: /data/data2/mc/DRAM/DRAM_data/kofam_profiles.hmm
KOfam KO list: /data/data2/mc/DRAM/DRAM_data/kofam_ko_list.tsv
UniRef db: None
Pfam db: /data/data2/mc/DRAM/DRAM_data/pfam.mmspro
dbCAN db: /data/data2/mc/DRAM/DRAM_data/dbCAN-HMMdb-V10.txt
RefSeq Viral db: /data/data2/mc/DRAM/DRAM_data/refseq_viral.20220527.mmsdb
MEROPS peptidase db: /data/data2/mc/DRAM/DRAM_data/peptidases.20220527.mmsdb
VOGDB db: /data/data2/mc/DRAM/DRAM_data/vog_latest_hmms.txt

Descriptions of search database entries
Pfam hmm dat: /data/data2/mc/DRAM/DRAM_data/Pfam-A.hmm.dat.gz
dbCAN family activities: /data/data2/mc/DRAM/DRAM_data/CAZyDB.07292021.fam-activities.txt
VOG annotations: /data/data2/mc/DRAM/DRAM_data/vog_annotations_latest.tsv.gz

Description db: /data/data2/mc/DRAM/DRAM_data/description_db.sqlite

DRAM distillation sheets
Genome summary form: /data/data2/mc/DRAM/DRAM_data/genome_summary_form.20220527.tsv
Module step form: /data/data2/mc/DRAM/DRAM_data/module_step_form.20220527.tsv
ETC module database: /data/data2/mc/DRAM/DRAM_data/etc_mdoule_database.20220527.tsv
Function heatmap form: /data/data2/mc/DRAM/DRAM_data/function_heatmap_form.20220527.tsv
AMG database: /data/data2/mc/DRAM/DRAM_data/amg_database.20220527.tsv

**Comment by rmFlynn** [comment]
Sorry for the delay @maocheng2020 I am looking into your problem now. it is not related to the no descriptions warning. I will see if I can suggest something in the new issue thread you made.
