### ISSUE TITLE
subprocess.CalledProcessError: Command '['mmseqs', 'createindex', '/data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/uniref90.20220505.mmsdb', '/data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/tmp', '--threads', '10']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by qinjunjun** [WrightonLabCSU/DRAM#175]
Thank you for DRAM, I met a issue when I load a databases.
 (DRAM) qinjunjun@dn1 /data1/qinjunjun/zhu_bingduzu $ DRAM-setup.py prepare_databases --output_dir  /data1/qinjunjun/zhu_bingduzu/DRAM_data
2022-05-05 13:13:47.324807: Database preparation started
Downloading dbCAN family activities from : https://bcb.unl.edu/dbCAN2/download/Databases/V10/CAZyDB.07292021.fam-activities.txt
Downloading dbCAN from: http://bcb.unl.edu/dbCAN2/download/dbCAN-HMMdb-V10.txt
0:00:38.725411: dbCAN database processed
Traceback (most recent call last):
  File "/data1/qinjunjun/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 158, in <module>
    args.func(**args_dict)
  File "/data1/qinjunjun/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 311, in prepare_databases
    output_dbs['uniref_db_loc'] = download_and_process_uniref(uniref_loc, temporary, uniref_version=uniref_version,
  File "/data1/qinjunjun/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 94, in download_and_process_uniref
    make_mmseqs_db(uniref_fasta_zipped, uniref_mmseqs_db, create_index=True, threads=threads, verbose=verbose)
  File "/data1/qinjunjun/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/utils.py", line 38, in make_mmseqs_db
    run_process(['mmseqs', 'createindex', output_loc, tmp_dir, '--threads', str(threads)], verbose=verbose)
  File "/data1/qinjunjun/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/utils.py", line 27, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/data1/qinjunjun/miniconda3/envs/DRAM/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'createindex', '/data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/uniref90.20220505.mmsdb', '/data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/tmp', '--threads', '10']' returned non-zero exit status 1.

**Comment by rmFlynn** [comment]
My first thought is that a download file is corrupt or MMseqs is not properly installed, try running `mmseqs createindex /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/uniref90.20220505.mmsdb /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/tmp --threads 10` That will give a more informative error

**Comment by qinjunjun** [comment]
> My first thought is that a download file is corrupt or MMseqs is not properly installed, try running `mmseqs createindex /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/uniref90.20220505.mmsdb /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/tmp --threads 10` That will give a more informative error

Thank you ,I will try your thought.

**Comment by qinjunjun** [comment]
> My first thought is that a download file is corrupt or MMseqs is not properly installed, try running `mmseqs createindex /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/uniref90.20220505.mmsdb /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/tmp --threads 10` That will give a more informative error

Hello,I try your way.
(DRAM) qinjunjun@dn1 /data1/qinjunjun/zhu_bingduzu $mmseqs createindex /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/uniref90.20220505.mmsdb /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/tmp --threads 10
createindex /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/uniref90.20220505.mmsdb /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/tmp --threads 10 

MMseqs Version:          	13.45111
Seed substitution matrix 	nucl:nucleotide.out,aa:VTML80.out
k-mer length             	0
Alphabet size            	nucl:5,aa:21
Compositional bias       	1
Max sequence length      	65535
Max results per query    	300
Mask residues            	1
Mask lower case residues 	0
Spaced k-mers            	1
Spaced k-mer pattern     	
Sensitivity              	7.5
k-score                  	0
Check compatible         	0
Search type              	0
Split database           	0
Split memory limit       	0
Verbosity                	3
Threads                  	10
Min codons in orf        	30
Max codons in length     	32734
Max orf gaps             	2147483647
Contig start mode        	2
Contig end mode          	2
Orf start mode           	1
Forward frames           	1,2,3
Reverse frames           	1,2,3
Translation table        	1
Translate orf            	0
Use all table starts     	false
Offset of numeric ids    	0
Create lookup            	0
Compressed               	0
Add orf stop             	false
Overlap between sequences	0
Sequence split mode      	1
Header split mode        	0
Strand selection         	1
Remove temporary files   	false

createindex /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/uniref90.20220505.mmsdb /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/tmp --threads 10 

MMseqs Version:          	13.45111
Seed substitution matrix 	nucl:nucleotide.out,aa:VTML80.out
k-mer length             	0
Alphabet size            	nucl:5,aa:21
Compositional bias       	1
Max sequence length      	65535
Max results per query    	300
Mask residues            	1
Mask lower case residues 	0
Spaced k-mers            	1
Spaced k-mer pattern     	
Sensitivity              	7.5
k-score                  	0
Check compatible         	0
Search type              	0
Split database           	0
Split memory limit       	0
Verbosity                	3
Threads                  	10
Min codons in orf        	30
Max codons in length     	32734
Max orf gaps             	2147483647
Contig start mode        	2
Contig end mode          	2
Orf start mode           	1
Forward frames           	1,2,3
Reverse frames           	1,2,3
Translation table        	1
Translate orf            	0
Use all table starts     	false
Offset of numeric ids    	0
Create lookup            	0
Compressed               	0
Add orf stop             	false
Overlap between sequences	0
Sequence split mode      	1
Header split mode        	0
Strand selection         	1
Remove temporary files   	false

indexdb /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/uniref90.20220505.mmsdb /data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/uniref90.20220505.mmsdb --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -k 0 --alph-size nucl:5,aa:21 --comp-bias-corr 1 --max-seq-len 65535 --max-seqs 300 --mask 1 --mask-lower-case 0 --spaced-kmer-mode 1 -s 7.5 --k-score 0 --check-compatible 0 --search-type 0 --split 0 --split-memory-limit 0 -v 3 --threads 10 

Target split mode. Searching through 43 splits
Estimated memory consumption: 25G
Write VERSION (0)
Write META (1)
Write SCOREMATRIX3MER (4)
Write SCOREMATRIX2MER (3)
Write SCOREMATRIXNAME (2)
Write SPACEDPATTERN (23)
Write GENERATOR (22)
Write DBR1INDEX (5)
Write DBR1DATA (6)
Write HDR1INDEX (18)
Write HDR1DATA (19)
Index table: counting k-mers
[=================================================================] 100.00% 2.07M 1m 23s 712ms      
Index table: Masked residues: 24683052
Index table: fill
/data1/qinjunjun/zhu_bingduzu/DRAM_data/database_files/tmp/4687820507331838815/createindex.sh: line 56: 1045504 Killed                  "$MMSEQS" $INDEXER "$INPUT" "$INPUT" ${INDEX_PAR}
Error: indexdb died

**Comment by rmFlynn** [comment]
I am so sorry this thread got lost in time. It looks like it was a corrupt database at the heart of it. Were you able to re download and process uniref? Again so sorry for the delay

**Comment by qinjunjun** [comment]
> I am so sorry this thread got lost in time. It looks like it was a corrupt database at the heart of it. Were you able to re download and process uniref? Again so sorry for the delay

Thank you ,I have got it .Thank you again.
