### ISSUE TITLE
How to prepare a single .pep KEGG database for DRAM database setup step

### ISSUE THREAD

**Issue by nixon444** [WrightonLabCSU/DRAM#182]
Hi,

I have a KEGG subscription and want to incorporate it into my DRAM setup. I tried setting up DRAM using a concatenation of the different .pep KEGG files to produce a single KEGG database DRAM didn't like it. It worked fine if only pointing to one of them.
 
What's the best way to combine these databases to make a single .pep file for DRAM setup? Or can I point to multiple .pep files upon configuration?

Thanks!

**Comment by rmFlynn** [comment]
Sorry for the late reply, and I am sorry that KEGG is so poorly documented. There are 2 ways, you can use the gene_ko_link_loc which should work with a concatenated pep file. I however like to use this script, it is easier to check. The kegg db can change on occasion, so it does require a more hands on approach. 

You can download the stuff you need with something like this. 
```
wget -r  -A "*\.pep\.gz" ftp://$UNAME:$PASS@ftp.kegg.net/kegg/genes/organisms
wget -r  -A "*\.kff\.gz" ftp://$UNAME:$PASS@ftp.kegg.net/kegg/genes/organisms

gzip -d ftp.kegg.net/kegg/genes/organisms/*/*pep.gz
gzip -d ftp.kegg.net/kegg/genes/organisms/*/*\.kff\.gz

cat ftp.kegg.net/kegg/genes/organisms/*/*pep >> kegg-all-orgs_20220129.pep
cat ftp.kegg.net/kegg/genes/organisms/*/*kff >> kegg-all-orgs_20220129.kff
```

If you have any problems at all, let me know, and I will walk you though it. I will be watching with interest
[remove_kegg_dups_and_rehead.py.gz](https://github.com/WrightonLabCSU/DRAM/files/8815751/remove_kegg_dups_and_rehead.py.gz)

**Comment by nixon444** [comment]
Hi, thanks for this!

Out of interest, do I need the .kff files to configure DRAM to use the corresponding KEGG databases? I have the following .pep files that I plan to concatenate and configure DRAM to use, but I can't see any equivalent .kff files on the KEGG server?

eukaryotes.pep.gz
family_eukaryotes.pep.gz
genus_eukaryotes.pep.gz
genus_prokaryotes.pep.gz
prokaryotes.pep.gz
species_prokaryotes.pep.gz
T10000.pep.gz
T40000.pep.gz

Thanks in advance!

**Comment by nixon444** [comment]
OK thanks, will concatenate these, attempt to de-duplicate, setup databases and report back!

**Comment by rmFlynn** [comment]
Good luck!

**Comment by pdn161** [comment]
Hi, thank you for the detailed instructions and for sharing your workflow — it's very helpful!

I wanted to ask: what should someone do if they don’t have a KEGG FTP account (i.e., no $UNAME and $PASS)?

As KEGG requires a paid subscription, many researchers (especially students or those from institutions without access) may not be able to download the .pep.gz and .kff.gz files directly using wget.

Are there any alternative ways to obtain these KEGG protein (*.pep) and KEGG gene function (*.kff) files for use with DRAM?
