### ISSUE TITLE
DRAM-setup.py error

### ISSUE THREAD

**Issue by wangyaxiang008** [WrightonLabCSU/DRAM#184]
Hello, thanks for designing such an excellent software. But I got the following error while using DRAM-setup.py command to prepare database.
![image](https://user-images.githubusercontent.com/54664252/173587118-f00d8a39-3c98-4eca-b7b2-14b890f780d1.png)

 I have downloaded more than 600 GB of data in my database_files directory. 
![image](https://user-images.githubusercontent.com/54664252/173587171-c9cfad50-d79d-4dd9-a7cf-9f8299cba075.png)
Should I re-run the command, or is there another better way?
thanks

**Comment by rmFlynn** [comment]
Can you try running that wget command at the end of your first screenshot on the command line and telling me what happens?

**Comment by wangyaxiang008** [comment]
I am very happy to get your reply！
Following your advice, I downloaded the ‘viral.2.protein.faa.gz.2’ file.
![image](https://user-images.githubusercontent.com/54664252/174696292-ba6d3db5-3763-4142-a2ee-dd8cd11facb6.png)
What should I do next?

thanks

**Comment by rmFlynn** [comment]
Looks like there is nothing wrong with that command, it was just a one time failure of your internet, if you run the setup again it may work this time, I assume you already did this? To more confidently avoid this error, run `DRAM-setup.py prepare_databases --output_dir DRAM_data --viral_loc <path to the file you just downloaded>`

**Comment by rmFlynn** [comment]
I know that it has only been a week, but I am going to close this issue as I don't think it is systemic, and I want this repository to be clean. Feel free to open it again if your issue is not resolved by any of those ideas.
