### ISSUE TITLE
Scipy error while downloading the databases

### ISSUE THREAD

**Issue by eray-sahin** [WrightonLabCSU/DRAM#191]
Hello,

I was desperately looking for any tool by which I can get functional annotation as I stucked after protein annotation. I re-discovered your tool to use on my contigs, however, I am having trouble at the beginning whilst trying to build databases because of an issue related to scipy package. When I try to execute 
`DRAM-setup.py prepare_databases --output_dir /dram/databases/`
getting error message of

_ImportError: cannot import name 'PearsonRConstantInputWarning' from 'scipy.stats' (anaconda3/envs/DRAM/lib/python3.10/site-packages/scipy/stats/__init__.py)_

@(https://github.com/biocore/scikit-bio/issues/1818), the response to this issue was "_A release is probably around October. Your best bet at the moment is to downgrade Scipy..._". I

Would removing the installed scipy version 1.9.0 and install any other older version than 1.3.0 create any problem in DRAM? Or do you have any other suggestion to overcomethat paroblem?

Thank you

**Comment by rmFlynn** [comment]
How interesting i have 1.8.1 with no problems, and that makes sense as this must be new for DRAM at least. So as long as it is pre 1.8.1 you are good. Thanks for bringing this to my attention.

**Comment by eray-sahin** [comment]
Removed v.1.9.0 and installed 1.8.1, and it is now working. Thank you :)

**Comment by rmFlynn** [comment]
Yes `DRAM.py annotate_genes -i your.faa` is the approximate command `DRAM.py annotate_genes --help` for more information. It skips making the gen bank file and is faster than the traditional method. It is not adequately documented.

**Comment by eray-sahin** [comment]
Dear @rmFlynn, thank you for your reply and info, I will try that. 

PS: As I opened this issue a day before the issue you replied, I am copying your reply to that issue for any future reference.

Best regards.

**Comment by SilasK** [comment]
Did you find a stable fix for this. I think there is now a new version of scikit-bio and this creates new conflicts. https://github.com/metagenome-atlas/atlas/issues/664
