### ISSUE TITLE
Database preparation error 3

### ISSUE THREAD

**Issue by woodoo46** [WrightonLabCSU/DRAM#195]
Hi there,

I am trying to run do database preparation as following:

DRAM-setup.py prepare_databases --output_dir ${outdir} --skip_uniref

But I had the following error:

subprocess.CalledProcessError: Command '['mmseqs', 'msa2profile', 'DRAM_data2/database_files/pfam.mmsmsa', 'DRAM_data2/database_files/pfam.mmspro', '--match-mode', '1', '--threads', '10']' returned non-zero exit status 3.

Thanks.

George

**Comment by rmFlynn** [comment]
Can you run `mmseqs msa2profile DRAM_data2/database_files/pfam.mmsmsa DRAM_data2/database_files/pfam.mmspro --match-mode 1 --threads 10` I need more information.

**Comment by woodoo46** [comment]
Thanks for your quick reply. I got it, it is because of lack of memory. Initially I ran as posted with 10 threads, it failed. I then tried with 2 threads, it used about 100g memory and still running.

George

**Comment by rmFlynn** [comment]
The memory problem is a big issue! Thanks!
