### ISSUE TITLE
Get DRAM version from command line

### ISSUE THREAD

**Issue by rujinlong** [WrightonLabCSU/DRAM#198]
Hi,

I'm wondering if it is possible to get DRAM version from command line? Although we can get it from the release history, a command like `DRAM.py --version` will be very helpful for reproducible data analysis when integrating DRAM into a pipeline. 

Thanks a lot.

**Comment by c-gr34sl3y** [comment]
_( Not associated with the project but i've built the application recently and was looking at another issue)_

There's a positional argument `version` for `DRAM-setup.py` that prints this.

`$ DRAM-setup.py version`
1.3.6

**Comment by rujinlong** [comment]
Thanks, Chris. This command works.
