### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by woodoo46** [WrightonLabCSU/DRAM#199]
Hi, there,

I ran DRAMv, and got the following error

 UserWarning: No descriptions were found for your id's. Does this YP_656630.1 look like an id from viral_description

I am not quite familiar with the viral database, any suggestions?

Thanks.

George

**Comment by rmFlynn** [comment]
Try `DRAM-setup.py --update_description_db` this usually solves this problem.

**Comment by woodoo46** [comment]
Thanks for your solution. This solves the key error. I am having another issue here:

  File "/tools/mylib/python-3.8.0-sqlite/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 495, in <dictcomp>
    for i in annotations.columns if i.endswith('_id')}
AttributeError: 'int' object has no attribute 'endswith'

**Comment by woodoo46** [comment]
By the way, this happens below this line:
**0:10:10.725917: Merging ORF annotations**

**Comment by rmFlynn** [comment]
Interesting, I thought we got this solved, what version of dram was it?

**Comment by woodoo46** [comment]
I am using 1.3.

**Comment by rmFlynn** [comment]
What is the output of `DRAM-setup.py version` ?

**Comment by woodoo46** [comment]
Yes. 1.3 is the output of DRAM-setup.py. I did not find options from DRAM-v.py or DRAM.py to print out the version information.

**Comment by rmFlynn** [comment]
If that is really the version please upgrade to 1.3.6, it should have the correct bug fix. If the problem persists on this version and you can upload the data you ran on please do so and I will find the bug immediately. You may also be able to fix this by manually editing the annotations file in Excel or similar, renaming the column that is 0 if it exists.

**Comment by woodoo46** [comment]
To upgrade to 1.3.6, do I need to git clone? I used the "Releases" link and downloaded 1.3. If I want to do the correction myself, namely "renaming the column that is 0 if it exists", where file(s) should change? I mean should change the python code or the annotation files?

Thanks.

**Comment by rmFlynn** [comment]
Sorry for the delay thing get lost hopfully you got 1.3.6 orherwise things will be fixed in 3.14 wich will hit conda soon.
