### ISSUE TITLE
Unable to view heatmap

### ISSUE THREAD

**Issue by MeggyC** [WrightonLabCSU/DRAM#200]
Hi there, 

I'm unable to see the heatmap of the AMGs from the dram-v distill part of the pipeline. Upon opening in my browser the page displays:

```
JavaScript Error: Maximum call stack size exceeded

This usually means there's a typo in your chart specification. See the javascript console for the full traceback.

```

Any tips? 

Additionally, in the amg_summary file, many of the putative AMGs don't have gene names/descriptions/associated IDs. Does this just mean that they are hypothetical proteins? 

Thanks and all the best

**Comment by yugen-miyahara** [comment]
I also couldn't get any visual output from my heatmaps either. Mine was just blank.

**Comment by rmFlynn** [comment]
Sorry I'm afk this week but my best guess is it is one of:
The distillation stopped to early/errors out
The file is to big -unlikly
This is a browser specific problem and chrome/fire fox will work.
There is a a unsupported character in one of the name of the genomes a none numeric/alphabetical character like (#& or {. And that is messing up the html. -best guess

**Comment by gauss1777** [comment]
Here are the file sizes of my two runs, the former can see the heatmap, but the latter can't.

amg_summary.tsv, 115 KB
product.html, 7,375 KB
vMAG_stats.tsv, 203 KB

amg_summary.tsv, 209 KB
product.html, 21,661 KB
vMAG_stats.tsv, 941 KB

I doubt that it may be related to the file size.

**Comment by rmFlynn** [comment]
Ok, I'm back, can you share your html file? Did you check for the other problems mentioned? Especially the alphanumeric characters?

**Comment by rmFlynn** [comment]
Inactive
