### ISSUE TITLE
Add ability to set location of config file

### ISSUE THREAD

**Issue by merrygoat** [WrightonLabCSU/DRAM#201]
After installing DRAM, it might be the case that the Python site-packages are in a non-writable location - for example on a shared HPC resource or when setting up DRAM in a Singularity or Docker container. The database setup stage of DRAM will then fail because the CONFIG file is not writeable.

I propose adding an environment variable which can set a new location for the CONFIG file. This addition would be backwards compatible, since it would use the exising behaviour if the environment variable was not present.

**Comment by HamzaMbareche** [comment]
Hi there,

I am precisely in the situation described by @merrygoat. I use DRAM in a singularity and Docker container in an HPC environment. I did get a non-writable error when trying to set up DRAM. Was the environment variable added? Can anyone help me figure out how to set up the environment variable by specifying a specific path?

For example, for snakemake, I had to specify the following:

`export XDG_CACHE_HOME=/scratch/c/croitoru/mbareche/`

Thank you, 
Hamza

**Comment by rmFlynn** [comment]
You can also use the command line argument added in the same release, if possible. In any case, if you fallow the merge, you will find the changes in the 1.4 release. [In the 1.4 of the release note, you can find the information you need in the 6th item in the change log](https://github.com/WrightonLabCSU/DRAM/releases/tag/v1.4.0). 

Thank you for using DRAM, I hope the new additions to the program, work for you.
