### ISSUE TITLE
series.append method is deprecated annd will be removed from pandas in a future version. ...

### ISSUE THREAD

**Issue by yolo2fh** [WrightonLabCSU/DRAM#205]
![a68b15104648ad050d06d19f0efcfb4](https://user-images.githubusercontent.com/112693830/188110485-8f61496d-0de4-4c34-99a1-0d6d82e90eb8.jpg)

A mistake is reported a when I used this software, so if this has run correctly ?
thanks~!

output:  amg_summary.tsv、product.html、vMAG_stats.tsv.

**Comment by rmFlynn** [comment]
This is Warning not a Error or a mistake. Pandas is updating and dram will remove the outdated method in the future, thanks for your patience.
