### ISSUE TITLE
kegg database

### ISSUE THREAD

**Issue by ucassee** [WrightonLabCSU/DRAM#210]
Hi,

I don't have access to the KEGG database, so I get a very low identification rate of AMGs for viruses. I guess this is because kofamscan has a very high threshold for assigning KO to proteins, which is not applicable to viruses. But kofamscan is good for prokaryotes. 
Would you provide me some headers of protein in kegg.pep. 

Thanks

**Comment by rmFlynn** [comment]
Sorry I can't provide information from kegg, we use kofam but not kofam scan in dram. I would not think that would be the primary problem for amgs however, as there are other databases. DRAM is relatively restrictive with respect to amgs in any case.
