### ISSUE TITLE
Wiki link to 404

### ISSUE THREAD

**Issue by cmkobel** [WrightonLabCSU/DRAM#214]
Hello

Thanks for maintaining DRAM

In the [wiki under section 3a DRAM distill](https://github.com/WrightonLabCSU/DRAM/wiki/3a.-Running-DRAM#dram-distill) there is a link to an example 

https://shafferm.github.io/examples/dram/

But that link goes to a 404 page on github.io

Sorry for spamming the issues tab.

**Comment by rmFlynn** [comment]
Thank you so much for this issue, I believe the bug has been fixed in all present cases. If you ever run into this again please let me know. Thank you again
