### ISSUE TITLE
About the viral gene flags "K" and "E" from DRAM-v

### ISSUE THREAD

**Issue by Jiulong-Zhao** [WrightonLabCSU/DRAM#218]
Dear developers,

Thanks for your great efforts in developing and maintaining this robust software for the viral AMG identifications.
Recently, I used this tool to scan my viral sequences and identified some viral AMGs related to Glycosyl hydrolases family 16 [PF00722.23] (pfam_hits in the annotation.tsv). I noticed that these viral AMGs were marked with flags "K" and "E", besides of the "M" and "F". You mentioned that the "K" and "E" mean these AMGs were reported and experimentally verified previously. So, I want to known  which literature reported and experimentally verified these AMGs. I didn't find any clues in the NAR paper and GitHub Wiki about this. Is there a database that deposit these reported AMGs and I can search from? 
I would appreciate it if you could provide some clues for me about this!

Thanks a lot!
Best wishes!

Jiulong

**Comment by jrr-microbio** [comment]
Hi Jiulong,

Thanks for your question.

The reference database that DRAM uses to flag all AMGs can be found on our GitHub here:
https://github.com/WrightonLabCSU/DRAM/blob/master/data/amg_database.tsv 

From that database, if you Ctrl-F search "Glycoside Hydrolase Family 16", it will show you the PFAM associated number (PF00722) as well as the reference(s) being cited for the experimental verification (Sun et al. 2000; Emerson et al. 2018). When applicable, it also shows the KO, E.C., and Kegg Module ID.

Please let us know if there's any way that we can help, and thanks for choosing DRAM!

Josué

**Comment by Jiulong-Zhao** [comment]
Hi @jrr-microbio,
Thanks for your kind and quick reply!
I have found what I need!
Thank you so much!
Jiulong
