### ISSUE TITLE
DRAM annotate_genes

### ISSUE THREAD

**Issue by trickovicmatija** [WrightonLabCSU/DRAM#233]
Hello,

My command is  
```console
DRAM.py annotate_genes -i path/to/genes_in_nt_fmt.fasta -o output_dir --threads 16
```
to annotate genes that I have previously grouped. I want to treat all genes in one fasta file as they belong to one genome and get the functional prediction on the pathway level.
I am experiencing a problem with the command:
```console
mmseqs createindex 1073/working_dir/1073001001_full_renamed/gene.mmsdb 1073/working_dir/1073001001_full_renamed/tmp --threads 16
```
There is no clear error message, but when I try to run the same command manually, the message is 
```console
"Database 1073/working_dir/1073001001_full_renamed/gene.mmsdb is a nucleotide database. Please provide the parameter --search-type 2 (translated) or 3 (nucleotide)."
```
When I provide the --search-type 2, it works.

Could it be a bug since "annotate_genes" is not widely used, or am I missing something?

Best and thanks,
Matija

**Comment by rmFlynn** [comment]
Are your genes not in amino acid format? The annotate_genes command only takes faa files.

**Comment by rmFlynn** [comment]
Sorry for the delay!

**Comment by rmFlynn** [comment]
This looks to be inactive, pleas open again if you run into the problem again.
