### ISSUE TITLE
Can I download the database manually?

### ISSUE THREAD

**Issue by chengzhongyi8** [WrightonLabCSU/DRAM#235]
Hello DRAM developers:
I have already installed the DRAM by anaconda. Then I need to set up the database. Because of the huge memory it needs, so i want to download the databases manually to save the cluster data. Thus, I want to know how to download these database (or the website and version of each database) ?

Cheers,
zhongy

**Comment by rmFlynn** [comment]
As long as you only do it occasionally this will work https://zenodo.org/record/7183884
