### ISSUE TITLE
Issue with downloading viral database (DRAM version 1.4.0)

### ISSUE THREAD

**Issue by Somebodyatthdoor** [WrightonLabCSU/DRAM#236]
Hi,

I tried a couple of times to download the DRAM databases using the newest version of DRAM (1.4.0 via conda). However, I am getting an error when trying to download the viral database:

2022-11-28 17:35:59,583 - Something went wrong with the download of the url: ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.1.protein.faa.gz
2022-11-28 17:35:59,583 - <urlopen error [Errno -2] Name or service not known>

DRAM does seem to have also tried to download the data from the http link (see full log attached).
[database_processing.log](https://github.com/WrightonLabCSU/DRAM/files/10111787/database_processing.log)

Thanks for your help,
Laura

**Comment by rmFlynn** [comment]
How annoying can you download the files from those links?  for example https://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.2.protein.faa.gz? If the problem persis
[viral.2.protein.faa.gz](https://github.com/WrightonLabCSU/DRAM/files/10134303/viral.2.protein.faa.gz)
ts then you can put them in a folder on your server and point to them using `DRAM-setup.py prepare_databases --viral_loc merged.faa.gz`  you can just cat the separate viral files together to make the merged.faa.gz
