### ISSUE TITLE
DRAM distill: AttributeError: 'Series' object has no attribute 'Note'

### ISSUE THREAD

**Issue by Cam-Baker** [WrightonLabCSU/DRAM#237]
Good morning,

Finding the following issue while running DRAM version 1.2.2 distill. Associated files are below (converted tsv to txt per github requirements). 

[project_trnas.txt](https://github.com/WrightonLabCSU/DRAM/files/10123560/project_trnas.txt)
[project_rrnas.txt](https://github.com/WrightonLabCSU/DRAM/files/10123561/project_rrnas.txt)
[project_annotations.txt](https://github.com/WrightonLabCSU/DRAM/files/10123562/project_annotations.txt)

Run command: `DRAM.py distill -i project_annotations.tsv -o genome_summaries --trna_path project_trnas.tsv --rrna_path project_rrnas.tsv`

Full output:

```
0:00:00.269025: Retrieved database locations and descriptions
0:00:00.343487: Calculated genome statistics
Traceback (most recent call last):
  File "/scratch/grc_group/.conda/envs/dram_1.2.2/bin/DRAM.py", line 153, in <module>
    args.func(**args_dict)
  File "/scratch/grc_group/.conda/envs/dram_1.2.2/lib/python3.9/site-packages/mag_annotator/summarize_genomes.py", line 609, in summarize_genomes
    summarized_genomes = make_genome_summary(annotations, genome_summary_form, trna_frame, rrna_frame,
  File "/scratch/grc_group/.conda/envs/dram_1.2.2/lib/python3.9/site-packages/mag_annotator/summarize_genomes.py", line 129, in make_genome_summary
    summary_frames.append(summarize_trnas(trna_frame, groupby_column))
  File "/scratch/grc_group/.conda/envs/dram_1.2.2/lib/python3.9/site-packages/mag_annotator/summarize_genomes.py", line 86, in summarize_trnas
    combos = {(line.Type, line.Codon, line.Note) for _, line in trnas_df.iterrows()}
  File "/scratch/grc_group/.conda/envs/dram_1.2.2/lib/python3.9/site-packages/mag_annotator/summarize_genomes.py", line 86, in <setcomp>
    combos = {(line.Type, line.Codon, line.Note) for _, line in trnas_df.iterrows()}
  File "/scratch/grc_group/.conda/envs/dram_1.2.2/lib/python3.9/site-packages/pandas/core/generic.py", line 5478, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'Note'
```

This is a small test project consisting of 5 samples. Any help would be appreciated.

Best,

Cameron

**Comment by rmFlynn** [comment]
How interesting, there is supposed to be a note column in the TSVs, and it seems to be missing. Do you think you could add a column into the tsvs with Excel or the like, and I will find out why this bug is present in the meantime? 

Also, it looks like the DRAM environment you are using is labeled 1.2.2 which is very very old, if you are not running DRAM 1.5.0 It would help me if you upgraded and tried again. Check using `DRAM-setup.py version`

**Comment by Cam-Baker** [comment]
Updated DRAM and this appears to have resolved this issue. It's curious as it was otherwise getting further with different sample sets. I'll reopen the ticket if it pops up again. 

Thanks for your help!

**Comment by rmFlynn** [comment]
Sounds good, do re-open if there is any trouble

**Comment by Cam-Baker** [comment]
Not a full re-open, but do you estimate how long it takes to build the DRAM database on the newer versions?

It's been plugging away for 9 days now, populating the description db at roughly 5KB/s.

**Comment by rmFlynn** [comment]
It depends on the databases you use and the speed of the disk it is on. If you have high speed scratch, use it! That said 9 days seems crazy it takes about 4h on my system.

**Comment by Cam-Baker** [comment]
I think all resources except for kegg. Plenty of RAM and CPUs and it's infiniband under the hood.

Perplexed but I'll let it chug
