### ISSUE TITLE
error with DRAM-setup.py prepare_databases

### ISSUE THREAD

**Issue by DrYoungOG** [WrightonLabCSU/DRAM#243]
Thanks for the useful software!
I have successfully installed DRAM in a conda environment naned "DRAM". 
Then I tried to run DRAM-setup.py prepare_databases to download the databases, but an error occured.

**The command I run:**
#!/bin/sh
#SBATCH --job-name=DRAM_db
#SBATCH --partition=cpuPartition
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=40
#SBATCH --error=/home/yangpc/DRAM_ref_db/download_db_script/DRAM_db.err
#SBATCH --output=/home/yangpc/DRAM_ref_db/download_db_script/DRAM_db.out
DRAM-setup.py prepare_databases --output_dir /home/yangpc/DRAM_ref_db --threads 40 --verbose

**output of command DRAM-setup.py print_config:**
2022-12-18 11:48:12,650 - Logging to console
/home/yangpc/anaconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_handler.py:124: UserWarning: Database does not exist at path None
  warnings.warn("Database does not exist at path %s" % description_loc)
Processed search databases
KEGG db: None
KOfam db: None
KOfam KO list: None
UniRef db: None
Pfam db: None
dbCAN db: None
RefSeq Viral db: None

MEROPS peptidase db: None
VOGDB db: None
Descriptions of search database entries
Pfam hmm dat: None
dbCAN family activities: None
VOG annotations: None

Description db: None

DRAM distillation sheets
Genome summary form: None
Module step form: None
ETC module database: None
Function heatmap form: None
AMG database: None

**DRAM-setup.py version:**
1.4.2

The .err file and .log file are attached.

Thank you very much!

[DRAM_db_err.txt](https://github.com/WrightonLabCSU/DRAM/files/10253310/DRAM_db_err.txt)
[database_processing.log](https://github.com/WrightonLabCSU/DRAM/files/10253311/database_processing.log)

**Comment by rmFlynn** [comment]
Dram 1.4.3 has a key bug fix. However, that may not be your problem, can you visit that url yourself.

**Comment by DrYoungOG** [comment]
I can download the two urls in the database_processing.log file and the DRAM_db_err.txt file(ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz, https://www.genome.jp/ftp/db/kofam/profiles.tar.gz), but what about other databases used in DRAM?

**Comment by rmFlynn** [comment]
So usually this is a fire wall issue, if you can't download any data bases the you can get the minimalist database from zotaro I will add that to the faq soon and send.

**Comment by rmFlynn** [comment]
So usually this is a fire wall issue, if you can't download any data bases the you can get the minimalist database from zotaro I will add that to the faq soon and send.

**Comment by DrYoungOG** [comment]
Please allow me to ask one more question, is there a solution to the fire wall issue?

**Comment by rmFlynn** [comment]
Sorry, for the delay, but the firewall would need to be fixed by your IT department the only advice I can give you is to use the loc arguments in dram prepare_databases to point to already downloaded data. You can download these by going to the needed website or from zenodo  https://zenodo.org/record/7183884
