### ISSUE TITLE
Strainer must be fully integrated with the logger and tested

### ISSUE THREAD

**Issue by WrightonLabAdmin** [WrightonLabCSU/DRAM#259]
There is an issue with strainers function calls not being integrated with the logger. @dmitrisvetlov Please fix this bug in DRAM one and send it to @rmFlynn for likely integration into DRAM2, please improve strainer documentation as you do so. This fix will be subject to code review prior to merging.
Tasks:

- Make a test for at least this use of strainer, and we can discuss more latter. This should include a small test file, well bellow drams size limits.
- Fix the function call to include logger.
- Add more documentation to the logger, like a Sphinx formatted doc string, and reduce the nesting.  
- Do a code review, and merge

**Comment by rmFlynn** [comment]
Link to github issue: https://github.com/WrightonLabCSU/DRAM/issues/259
Why was this issue closed on github?
