### ISSUE TITLE
KEGG reformatting regarding to #182

### ISSUE THREAD

**Issue by SF-Dragon** [WrightonLabCSU/DRAM#273]
For reformatting the KEGG gene database, the provided script "emove_kegg_dups_and_rehead.py"  generated the following error.  I wonder how this issue can be solved.

root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/achi has a kff but no pep files
root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/achl has no data
root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/acho has no data
root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/achr has no data
root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/index.html has no data
root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/index.html?C=D;O=A has no data
root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/index.html?C=D;O=D has no data
root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/index.html?C=M;O=A has no data
root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/index.html?C=M;O=D has no data
root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/index.html?C=N;O=A has no data
root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/index.html?C=N;O=D has no data
root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/index.html?C=S;O=A has no data
root        : ERROR     The folder ftp.kegg.net/kegg/genes/organisms/index.html?C=S;O=D has no data
root        : CRITICAL The program will end execution because there may be errors in downloading.
Traceback (most recent call last):
  File "/Volumes/remove_kegg_dups_and_rehead.py", line 157, in <module>
    raise ValueError("System exiting see logs for why.")
ValueError: System exiting see logs for why.

**Comment by jrr-microbio** [comment]
See this entry for help relating to KEGG database formatting: https://github.com/WrightonLabCSU/DRAM/issues/305
