### ISSUE TITLE
Is --gene_ko_link_loc necessary if I used --kegg_loc ?

### ISSUE THREAD

**Issue by mol529** [WrightonLabCSU/DRAM#284]
Hello!
I have been trying to set up the DRAM databases with KEGG. 
The gene sequence names in the  KEGG database file only contain gene Entry, like this:  >melm:C7H73_11415
It doesn't contain the KO number.  Must  I  specify a  gene_ko_link file ?

**Comment by jrr-microbio** [comment]
See this entry for help relating to KEGG database formatting: https://github.com/WrightonLabCSU/DRAM/issues/305
