### ISSUE TITLE
DRAM distill output errors: almost all values are zeros

### ISSUE THREAD

**Issue by Somebodyatthdoor** [WrightonLabCSU/DRAM#287]
Hi,

I am having an unusual problem when running dram distill.  I end up with a summary that has zero values for practically all of my MAGs . 
[metabolism_summary.xlsx](https://github.com/WrightonLabCSU/DRAM/files/12026841/metabolism_summary.xlsx). But when I look in the annotate.tsv file there are clearly genes that are annotated with some of the functions described as "0.0" in the metabolism summary file. So I think it is a problem with the distill command, rather than with the annotation. 

I do get some errors when running dram distill ([dram_distill_drep_err.txt](https://github.com/WrightonLabCSU/DRAM/files/12026871/dram_distill_drep_err.txt)), but I don't see why any of them would cause this problem. 

I am using dram v1.4.6. 

Any advice you can give would be appreciated.

Cheers,
Laura

**Comment by BioRRW** [comment]
Apologies for the late reply but thank your for reaching out.
Which databases did you use to annotate? - KEGG formatting can result in this issue.

Good luck and keep us posted

**Comment by jrr-microbio** [comment]
See this entry for help relating to KEGG database formatting: https://github.com/WrightonLabCSU/DRAM/issues/305

**Comment by Somebodyatthdoor** [comment]
Thank you both for your comments. 

I have been using an oldish version of KEGG, so I'll give your suggestion a try. 

Cheers,
Laura
