### ISSUE TITLE
scikit-bio release 0.5.9 brings up ImportError.

### ISSUE THREAD

**Issue by SebaSilvaS** [WrightonLabCSU/DRAM#293]
Hello! 
I would like to point out the new release of scikit-bio (from two weeks ago). It has an incompatibility with scipy 1.8.1, raising the following error: 

`ImportError:` cannot import name 'ConstantInputWarning' from 'scipy.stats' (~/envs/DRAM/lib/python3.10/site-packages/scipy/stats/__init__.py)`

EDIT:
There are conflicts if 0.5.8 is set explicitly in the environment.yaml. Could anyone share a working environment yaml file, please?

**Comment by 778055611** [comment]
I try to modify the yaml file like the following,then ,I solved this question
```python
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.8
  - pandas
  - pytest
  - scikit-bio==0.5.6
  - prodigal
  - mmseqs2==13.45111
  - hmmer!=3.3.1
  - trnascan-se >=2
  - scipy<=1.8.0
  - sqlalchemy
  - barrnap
  - altair >=4
  - openpyxl
  - networkx
  - ruby
  - parallel
  - dram
```

**Comment by BioRRW** [comment]
Apologies for the wait. We have a new release coming, v1.5.0, to address some of the recent issues.
In the meantime, the environment.yaml has been updated to resolve this issue.
