### ISSUE TITLE
I have some trouble in using DRAM.py annotate 

### ISSUE THREAD

**Issue by microbial-cookie** [WrightonLabCSU/DRAM#309]
Hi DRAM developers, 

I have some trouble in using DRAM.py annotate 

![image](https://github.com/WrightonLabCSU/DRAM/assets/133230591/ef364dde-fbc0-441e-bef7-426af8065742)

please help me!!!

**Comment by BioRRW** [comment]
Hi, sorry for the late response.

I am not sure of an immediate solution - but will work to figure this out with you.
What conda environment did you build? There was an updated conda environment.yaml file uploaded which contains specific versions of the dependencies. If you have not tried to update your conda environment, I would try this first. 

Best of luck and let us know how it goes.

**Comment by microbial-cookie** [comment]
Hi developer, 
 According to your suggestions, I used the Command  " conda activate  DRAM" and "conda env update --file environment.yaml --prune" to update my conda environment, but I failed.
The error information is below:

The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::pysocks==1.7.1=pyha2e5f31_6
  - conda-forge/noarch::urllib3==2.0.4=pyhd8ed1ab_0
  - conda-forge/noarch::requests==2.31.0=pyhd8ed1ab_0
  - conda-forge/noarch::cachecontrol==0.13.1=pyhd8ed1ab_0
  - conda-forge/noarch::ipython==8.15.0=pyh0d859eb_0
  - conda-forge/linux-64::scikit-bio==0.5.9=py310h278f3c1_0
  - bioconda/noarch::dram==1.4.6=pyhdfd78af_0
failed

ResolvePackageNotFound:
  - parallel=20221122
  - sqlalchemy=1.4.46

how do I solve these inconsistencies, maybe, is reinstalling everything of DRAM from scratch the quickest solution? My mood is collapsing. Moreover, my another previous question was not solved, which was about database setup (error #298), please help me, thanks a lot!

**Comment by BioRRW** [comment]
Hi, I am sorry to here about the conflicts.
Unfortunately, yes. If this is the solution then re-installing DRAM will be the best solution. 
I would create a new conda environment using the updated YAML recipe file.

**Comment by 778055611** [comment]
> Hi, I am sorry to here about the conflicts. Unfortunately, yes. If solving the conflicts within the conda environment cannot be done then re-installing DRAM will be the best solution. I would create a new conda environment using the updated YAML recipe file.

hello，developer,thank you for develop such useful tools ,could you please check my issue [https://github.com/WrightonLabCSU/DRAM/issues/307]

**Comment by microbial-cookie** [comment]
Hi developer,

I have solved this problem via using the updated YAML recipe file to re-installing DRAM, thanks a lot!
