### ISSUE TITLE
Figure output missing

### ISSUE THREAD

**Issue by moyn413** [WrightonLabCSU/DRAM#311]
Hi, I've successfuly run DRAM.py annotate and DRAM.py distill. However, in my output files, I don't see the electron chain coverage figures or the pathway figures that are shown in "[4a. Interpreting the Results of DRAM](https://github.com/WrightonLabCSU/DRAM/wiki/4a.-Interpreting-the-Results-of-DRAM)". Is it necessary to have KEGG database access setup to generate these figures? Thank you!

**Comment by jrr-microbio** [comment]
Hi there, 

Unfortunately, yes. The DRAM distillation step uses results from KEGG pretty heavily to make the final product with regards to the electron transport chain and respiration complexes. You can find gene identifiers and gene names that DRAM uses to call all of the things in the product heatmap here: [DRAM Genome summary form](https://github.com/WrightonLabCSU/DRAM/blob/master/data/genome_summary_form.tsv). In theory, you could try find those manually using the other databases and searching for the related genes.
