### ISSUE TITLE
Peptidase database

### ISSUE THREAD

**Issue by VictorBorin** [WrightonLabCSU/DRAM#64]
Hello, I install DRAM using conda recently. When I run the annotate command, it shows the error:
DRAM.py annotate -i 'test/*.fna' -o annotation --threads 10
2 fastas found
2021-02-16 11:54:54.257147: Annotation started
0:00:00.040343: Retrieved database locations and descriptions
0:00:00.040376: Annotating METABAT_84
0:01:48.909865: Turning genes from prodigal to mmseqs2 db
0:01:51.289461: Getting hits from kofam
0:21:55.120991: Getting forward best hits from peptidase
0:22:19.253644: Getting reverse best hits from peptidase
0:22:21.115586: Getting descriptions of hits from peptidase
/opt/Miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py:42: UserWarning: No descriptions were found for your id's. Does this MER0378710 look like an id from peptidase_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
Traceback (most recent call last):
  File "/opt/Miniconda3/envs/DRAM/bin/DRAM.py", line 145, in <module>
    args.func(**args_dict)
  File "/opt/Miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 963, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/opt/Miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1000, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, prodigal_mode,
  File "/opt/Miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 919, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/opt/Miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 820, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/opt/Miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 754, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_locs['peptidase'], tmp_dir,
  File "/opt/Miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 655, in do_blast_style_search
    hits = get_description(hits, header_dict)
  File "/opt/Miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 175, in get_peptidase_description
    header = header_dict[peptidase_hit]
KeyError: 'MER0378710'

I had to manually put the database's path because the prepare_database command did not do this for me. Here are the settings:
KEGG db: None
KOfam db: /data/DRAM_data/kofam_profiles.hmm
KOfam KO list: /data/DRAM_data/kofam_ko_list.tsv
UniRef db: /data/DRAM_data/uniref90.20210216.mmsdb
Pfam db: /data/DRAM_data/pfam.mmspro
Pfam hmm dat: /data/DRAM_data/Pfam-A.hmm.dat.gz
dbCAN db: /data/DRAM_data/dbCAN-HMMdb-V8.txt
dbCAN family activities: /data/DRAM_data/CAZyDB.07312019.fam-activities.txt
RefSeq Viral db: /data/DRAM_data/refseq_viral.20210216.mmsdb
MEROPS peptidase db: /data/DRAM_data/peptidases.20210216.mmsdb
VOGDB db: /data/DRAM_data/vog_latest_hmms.txt
VOG annotations: /data/DRAM_data/vog_annotations_latest.tsv.gz
Description db: /data/DRAM_data/description_db.sqlite
Genome summary form: /data/DRAM_data/genome_summary_form.20210216.tsv
Module step form: /data/DRAM_data/module_step_form.20210216.tsv
ETC module database: /data/DRAM_data/etc_mdoule_database.20210216.tsv
Function heatmap form: /data/DRAM_data/function_heatmap_form.20210216.tsv
AMG database: /data/DRAM_data/amg_database.20210216.tsv

Thank you

**Comment by shafferm** [comment]
Hello,

When you ran `DRAM-setup.py prepare_databases` did it finish with an error or did it not have the MEROPs database in place even after finishing successfully?

My hunch is that for some reason the MEROPs identifiers didn't get added to the database. As a result you will need to rebuild the description database. You can do this by running `DRAM-setup.py update_description_db`.

**Comment by VictorBorin** [comment]
> Hello,
> 
> When you ran `DRAM-setup.py prepare_databases` did it finish with an error or did it not have the MEROPs database in place even after finishing successfully?
> 
> My hunch is that for some reason the MEROPs identifiers didn't get added to the database. As a result you will need to rebuild the description database. You can do this by running `DRAM-setup.py update_description_db`.

Hi, thank you for the quick reply.

I not exactly sure because I run the `DRAM-setup.py prepare_databases` with "nohup and &". My nohup file was empty, so no error.

I tried to do the DRAM-setup.py update_description_db:
0:00:00.000004: Populating description database
0:00:01.476084: Database connection established
0:00:01.476123: KEGG descriptions added to description database
Dead

It seems a problem with Memory.

**Comment by shafferm** [comment]
Hmm. Can you try running with more memory available if you have some. @mw55309 also created some scripts to deal with this issue that you could try out https://github.com/mw55309/DRAM_hacks.
