### ISSUE TITLE
DRAM on viral contigs instead of DRAM-v

### ISSUE THREAD

**Issue by miasungeunlee** [WrightonLabCSU/DRAM#65]
Hi Michael,
First, thank you for developing this nice tool !
I'm writing this message to make sure what i'm doing is correct or not and get some your advice. 
I used this tool for annotating AMGs on two different viromes (two fasta files) containing viral contigs predicted using both VirSorter and DeepVirFinder. As DeepVirFinder do not provide the VIRSorter_affi-contigs.tab file, i run DRAM on these two fasta file instead of using DRAN-v. I know that this tool is for individual MAG (bin), but i'm not looking at AMGs on individual viral contigs yet, but just looking at global AMGs on two different viromes containing different viral contigs. 
It worked perfectly fine, there was no detection of rRNAs which is great as those are all viral origin and this tool allowed identifying the presence or absence of specific AMGs involving in different CAZy categories and alcohol production category within two different viromes. Do you think it is okay or correct to use like what i did ? 

Many thanks
Mia
PS. Oh, just found your comment that we can use Virsorter2 tool for generating the file !

**Comment by shafferm** [comment]
Hi Mia,

DRAM-v currently requires the VIRSorter_affi-contigs.tab file as can be generated by VirSorter or VirSorter2 to predict AMGs. You can still annotate your viruses but you won't get predicted AMGs. This is further discussed here #35. I would be cautious about calling a gene an AMG without determining how confident you are that a gene is viral in origin. Tools like VirSorter and DeepVirFinder often leave microbial genes on the ends of contigs in the case of proviruses and these can appear to be AMGs if you don't do something like use DRAM-v's auxiliary (which requires the affi-contigs file to generate) or do trimming of your contigs with something like checkV. Additionally many genes with KEGG or CAZy hits can look like they are metabolic functions but really are known to be used by viruses. If you annotated using DRAM-v even without the affi-contigs file you will get a column called `amg_flags` which can give you a clue about if we think that gene is metabolic and non-viral in origin but we won't tell you if it is a potential AMG or not without that affi-contigs file..

Hope this helps!

Mike

**Comment by miasungeunlee** [comment]
Hi Mike, 
Many thanks for your comments, super clear and useful. 
I didn't know that DRAM-v can run without without the affi-contigs file. 
FYI, I predicted viral contigs using VirSorter and DVF, but by using updated VirSorter 2.0, most of predicted vOTUs (98%) were recovered as viral, which is so nice. So i could run DRAM-v with the affi-contigs file. 
If not, for other vOTUs that were not recovered as viral using VirSorter 2.0, i'll manually check the position of AMGs and also their gene content to verify if they are real viruses or real AMGs. 
Have a nice week-end :) 
Mia
