### ISSUE TITLE
How to add classification for each genome in the html heatmap

### ISSUE THREAD

**Issue by jianshu93** [WrightonLabCSU/DRAM#68]
Hello,

I am wondering how to add classification information for each genome like in the NAR paper in the html heatmap output.

Thanks,

Jianshu

**Comment by shafferm** [comment]
The names shown in the product (the html heatmap) are the names of your bins. So you can change the names of your bins before annotating or change the values for the `fasta` column in your `annotations.tsv` and those are what will show up in the product. DRAM will also add full taxonomy strings before the presence/absence heatmap if you provide GTDB-tk output to your annotation.

**Comment by Anto007** [comment]
Impressive tool and many thanks for coming up with this! I noticed that in my product.html, gtdb taxonomy strings are only added to the Cazy heatmaps and so on but not the heatmaps representing the central metabolism and ETC complex modules. Those heatmaps oddly carry the bin/fasta file names. My command-line was- `DRAM.py annotate -i 'MAGs/*.fasta' -o annotation --min_contig_size 1000 --gtdb_taxonomy gtdbtk.bac120.summary.tsv --checkm_quality checkm_results`

**Comment by rmFlynn** [comment]
@shafferm it looks like this is coded into the product generating functions, and could be changed. I am curious why it is this way? Are we trying to ensure the connections to the bins is not lost?

**Comment by rmFlynn** [comment]
Yes that is the idea more or less
