### ISSUE TITLE
How to restart the 'prepare_databases' processes after some errors?

### ISSUE THREAD

**Issue by Jiulong-Zhao** [WrightonLabCSU/DRAM#73]
Hi developers,

Recently, I tried to prepare the needed databases of DRAM, but it seems something wrong was happening.

The error information of the 'DRAM-setup.py' command was followed:
`(DRAM) [mcs@mcs1 DRAM]$ DRAM-setup.py prepare_databases --output_dir ~/database/DRAM_data
2021-03-29 09:13:11.305543: Database preparation started
20:36:27.784819: UniRef database processed
22:28:34.709378: PFAM database processed
22:29:39.322001: dbCAN database processed
22:30:16.506336: RefSeq viral database processed
22:34:31.739932: MEROPS database processed
22:37:01.370102: VOGdb database processed
22:47:05.273895: KOfam database processed
22:47:13.026326: KOfam ko list processed
22:47:21.325289: PFAM hmm dat processed
22:47:27.366145: dbCAN fam activities processed
22:47:29.549721: VOGdb annotations processed
Traceback (most recent call last):
  File "/home/mcs/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/mcs/soft/DRAM/scripts/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/home/mcs/soft/DRAM/mag_annotator/database_processing.py", line 496, in prepare_databases
    output_dbs['genome_summary_form_loc'] = download_and_process_genome_summary_form(temporary, branch, verbose)
  File "/home/mcs/soft/DRAM/mag_annotator/database_processing.py", line 268, in download_and_process_genome_summary_form
    download_file('https://raw.githubusercontent.com/shafferm/DRAM/%s/data/genome_summary_form.tsv' % branch,
  File "/home/mcs/soft/DRAM/mag_annotator/utils.py", line 27, in download_file
    run_process(['wget', '-O', output_file, url], verbose=verbose)
  File "/home/mcs/soft/DRAM/mag_annotator/utils.py", line 38, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/home/mcs/miniconda3/envs/DRAM/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wget', '-O', '/home/mcs/database/DRAM_data/database_files/genome_summary_form.20210330.tsv', 'https://raw.githubusercontent.com/shafferm/DRAM/master/data/genome_summary_form.tsv']' returned non-zero exit status 4.
`
This might be caused by the network limitation so that I can not download the 'genome_summary_form.tsv' file.

That's OK. I download this file and upload it to the server manually.

But when I tried to restart the 'DRAM-setup.py' command to continue the database preparation, the error message was like this:
`(DRAM) [mcs@mcs1 database_files]$ DRAM-setup.py prepare_databases --output_dir ~/database/DRAM_data
2021-04-01 13:45:47.933202: Database preparation started
Traceback (most recent call last):
  File "/home/mcs/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/mcs/soft/DRAM/scripts/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/home/mcs/soft/DRAM/mag_annotator/database_processing.py", line 448, in prepare_databases
    mkdir(temporary)
FileExistsError: [Errno 17] File exists: '/home/mcs/database/DRAM_data/database_files'
`  

So, how can I continue the 'prepare_databases' without deleting the older folder?

Also, are there some similar commands like "'wget https://raw.githubusercontent.com/..."  in the following steps of the 'prepare_databases'?  How to solve this problem?

Thanks for all your effect on this software! 
Looking forward to your reply! 

Best wishes 
Jiulong

**Comment by Jiulong-Zhao** [comment]
Hi developers,

After I met that problem mentioned above, I tried to restart the job into a new folder, and I downloaded and uploaded the needed data files: 'module_step_form.tsv',  'etc_module_database.tsv', 'function_heatmap_form.tsv', and 'genome_summary_form.tsv' manually.

The following command was typed:
`
DRAM-setup.py prepare_databases --output_dir ~/database/DRAM_data_new --skip_uniref --threads 20 --pfam_hmm_dat ~/database/DRAM_data/Pfam-A.hmm.dat.gz --vog_annotations ~/database/DRAM_data/vog_annotations_latest.tsv.gz --verbose --dbcan_fam_activities ~/database/DRAM_data/CAZyDB.07302020.fam-activities.txt --pfam_loc /home/mcs/database/DRAM_data/database_files/Pfam-A.full.gz --dbcan_loc /home/mcs/database/DRAM_data/database_files/dbCAN-HMMdb-V9.txt --vogdb_loc /home/mcs/database/DRAM_data/database_files/vog.hmm.tar.gz --viral_loc /home/mcs/database/DRAM_data/database_files/viral.merged.protein.faa.gz --genome_summary_form_loc /home/mcs/database/DRAM_data/database_files/genome_summary_form.tsv --module_step_form_loc /home/mcs/database/DRAM_data/database_files/module_step_form.tsv --etc_module_database_loc /home/mcs/database/DRAM_data/database_files/etc_module_database.tsv --function_heatmap_form_loc /home/mcs/database/DRAM_data/database_files/function_heatmap_form.tsv --peptidase_loc /home/mcs/database/DRAM_data/database_files/merops_peptidases_nr.faa
`
But, the error was reported again:
`Traceback (most recent call last):
  File "/home/mcs/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/mcs/soft/DRAM/scripts/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/home/mcs/soft/DRAM/mag_annotator/database_processing.py", line 526, in prepare_databases
    set_database_paths(**output_dbs, use_current_locs=False, update_description_db=True, start_time=start_time)
  File "/home/mcs/soft/DRAM/mag_annotator/database_processing.py", line 350, in set_database_paths
    db_dict = check_exists_and_add_to_location_dict(description_db_loc, 'description_db', db_dict)
  File "/home/mcs/soft/DRAM/mag_annotator/database_processing.py", line 303, in check_exists_and_add_to_location_dict
    if check_file_exists(loc):
  File "/home/mcs/soft/DRAM/mag_annotator/database_processing.py", line 34, in check_file_exists
    raise ValueError("Database location does not exist: %s" % db_loc)
ValueError: Database location does not exist: /home/mcs/database/DRAM_data_new/description_db.sqlite`

I do not know why this problem happened and really need your help! 
The whole log was: 
[log.txt](https://github.com/shafferm/DRAM/files/6247882/log.txt)

Thanks again!
Looking forward to your reply!

Best wishes
Jiulong

**Comment by shafferm** [comment]
You found a bug in my refactoring. I will push out a fix for this ASAP. To get around this you can run `DRAM-setup.py set_database_locations` using the `--update_description_db` flag. You will need to set all the flags for kofam, pfam, dbcan, vogdb, viral db, peptidases and all the DRAM file locations. If you send me the results of running `ls` on your '~/database/DRAM_data_new` directory then I can help you write it.

**Comment by Jiulong-Zhao** [comment]
Hi Shafferm,

Thanks for your kind reply!

These are the files in the directory '~/database/DRAM_data':

`amg_database.20210402.tsv
CAZyDB.07302020.fam-activities.txt
database_files/
dbCAN-HMMdb-V9.txt
dbCAN-HMMdb-V9.txt.h3f
dbCAN-HMMdb-V9.txt.h3i
dbCAN-HMMdb-V9.txt.h3m
dbCAN-HMMdb-V9.txt.h3p
etc_module_database.tsv
function_heatmap_form.tsv
genome_summary_form.tsv
kofam_ko_list.tsv
kofam_profiles.hmm
kofam_profiles.hmm.h3f
kofam_profiles.hmm.h3i
kofam_profiles.hmm.h3m
kofam_profiles.hmm.h3p
module_step_form.tsv
peptidases.20210402.mmsdb
peptidases.20210402.mmsdb.dbtype
peptidases.20210402.mmsdb_h
peptidases.20210402.mmsdb_h.dbtype
peptidases.20210402.mmsdb_h.index
peptidases.20210402.mmsdb.idx
peptidases.20210402.mmsdb.idx.dbtype
peptidases.20210402.mmsdb.idx.index
peptidases.20210402.mmsdb.index
peptidases.20210402.mmsdb.lookup
peptidases.20210402.mmsdb.source
Pfam-A.hmm.dat.gz
pfam.mmspro
pfam.mmspro.dbtype
pfam.mmspro_h
pfam.mmspro_h.dbtype
pfam.mmspro_h.index
pfam.mmspro.idx
pfam.mmspro.idx.dbtype
pfam.mmspro.idx.index
pfam.mmspro.index
refseq_viral.20210402.mmsdb
refseq_viral.20210402.mmsdb.dbtype
refseq_viral.20210402.mmsdb_h
refseq_viral.20210402.mmsdb_h.dbtype
refseq_viral.20210402.mmsdb_h.index
refseq_viral.20210402.mmsdb.idx
refseq_viral.20210402.mmsdb.idx.dbtype
refseq_viral.20210402.mmsdb.idx.index
refseq_viral.20210402.mmsdb.index
refseq_viral.20210402.mmsdb.lookup
refseq_viral.20210402.mmsdb.source
vog_annotations_latest.tsv.gz
vog_latest_hmms.txt
vog_latest_hmms.txt.h3f
vog_latest_hmms.txt.h3i
vog_latest_hmms.txt.h3m
vog_latest_hmms.txt.h3p
`

In case you need more information, the files in the directory '~/database/DRAM_data/database_files' are followed:
`kofam_profiles/
merops_peptidases_nr.faa
pfam.mmsmsa
pfam.mmsmsa.index
viral.1.protein.faa.gz
viral.merged.protein.faa.gz
vog.hmm.tar.gz
kofam_profiles.tar.gz
Pfam-A.full.gz
pfam.mmsmsa.dbtype
tmp/
viral.2.protein.faa.gz
vogdb_hmms/`

Thanks again!

Jiulong

**Comment by shafferm** [comment]
I think I have found the issue and fixed it. I'm testing now and if that works I will push a fix. To finish set up before that you can run these commands:

```
DRAM-setup.py set_database_locations --kofam_hmm_loc ~/database/DRAM_data_new/kofam_profiles.hmm \
                                     --pfam_db_loc ~/database/DRAM_data_new/pfam.mmspro \
                                     --pfam_hmm_dat ~/database/DRAM_data_new/Pfam-A.hmm.dat.gz \
                                     --dbcan_db_loc ~/database/DRAM_data_new/dbCAN-HMMdb-V9.txt \
                                     --dbcan_fam_activities ~/database/DRAM_data_new/CAZyDB.07302020.fam-activities.txt \
                                     --vogdb_db_loc ~/database/DRAM_data_new/vog_latest_hmms.txt \
                                     --viral_db_loc ~/database/DRAM_data_new/refseq_viral.20210402.mmsdb \
                                     --peptidase_db_loc ~/database/DRAM_data_new/peptidases.20210402.mmsdb \
                                     --genome_summary_form_loc ~/database/DRAM_data_new/genome_summary_form.tsv \
                                     --module_step_form_loc ~/database/DRAM_data_new/module_step_form.tsv \
                                     --etc_module_database_loc ~/database/DRAM_data_new/etc_mdoule_database.tsv \
                                     --function_heatmap_form_loc ~/database/DRAM_data_new/function_heatmap_form.tsv \
                                     --amg_database_loc ~/database/DRAM_data_new/amg_database.tsv

DRAM-setup.py update_description_db --output_loc ~/database/DRAM_data_new/description_db.sqlite

```

**Comment by emboismier** [comment]
Hi, I experienced the same issue. Should I delete my DRAM_data directory and re-install DRAM to start the set-up again since it has been fixed?

**Comment by Jiulong-Zhao** [comment]
Hi @shafferm , 

As you suggested, I run the command you provided, and it seems like finished successfully!

I want to know whether the setup process of databases is finished or not. Are there any other works to do to finish this process? 
 
Can I then run the software to work on my data?

Thank you so much!

Best， 
Jiulong

**Comment by Jiulong-Zhao** [comment]
Hi @shafferm ，
I tried to run the soft by the following command to check whether the database setup is finished or not:
`DRAM-v.py annotate -i final-viral-combined-for-dramv.fa -v viral-affi-contigs-for-dramv.tab -o annotation`

Unfortunately, the error message has arisen:
`2021-04-10 22:25:36.827732: Viral annotation started
Traceback (most recent call last):
  File "/home/mcs/miniconda3/envs/DRAM/bin/DRAM-v.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/mcs/soft/DRAM/scripts/DRAM-v.py", line 140, in <module>
    args.func(**args_dict)
  File "/home/mcs/soft/DRAM/mag_annotator/annotate_vgfs.py", line 374, in annotate_vgfs
    db_handler = DatabaseHandler(db_locs['description_db'])
  File "/home/mcs/soft/DRAM/mag_annotator/database_handler.py", line 17, in __init__
    raise ValueError('Database does not exist at path %s' % database_loc)
ValueError: Database does not exist at path None
`

I run the `DRAM-setup.py print_config` to check the locations of databases, but it seems like that there are still some databases without any location.
`(DRAM) [mcs@mcs1 for-dramv]$ DRAM-setup.py print_config
KEGG db: None
KOfam db: /home/mcs/database/DRAM_data/kofam_profiles.hmm
KOfam KO list: None
UniRef db: None
Pfam db: /home/mcs/database/DRAM_data/pfam.mmspro
Pfam hmm dat: /home/mcs/database/DRAM_data/Pfam-A.hmm.dat.gz
dbCAN db: /home/mcs/database/DRAM_data/dbCAN-HMMdb-V9.txt
dbCAN family activities: /home/mcs/database/DRAM_data/CAZyDB.07302020.fam-activities.txt
RefSeq Viral db: /home/mcs/database/DRAM_data/refseq_viral.20210402.mmsdb
MEROPS peptidase db: /home/mcs/database/DRAM_data/peptidases.20210402.mmsdb
VOGDB db: /home/mcs/database/DRAM_data/vog_latest_hmms.txt
VOG annotations: None
Description db: None
Genome summary form: /home/mcs/database/DRAM_data/genome_summary_form.tsv
Module step form: /home/mcs/database/DRAM_data/module_step_form.tsv
ETC module database: /home/mcs/database/DRAM_data/etc_module_database.tsv
Function heatmap form: /home/mcs/database/DRAM_data/function_heatmap_form.tsv
AMG database: /home/mcs/database/DRAM_data/amg_database.20210402.tsv
`
So, what should I do next?

I can not be appreciated for that more.

Best wishes,
Jiulong

**Comment by shafferm** [comment]
Okay! I have figure it out and pushed a fix! You can install it right now with pip or in a day or two via conda. After you do this you will be able to run that `set_database_locations` and `update_description_db` command and it should all work.

**Comment by emboismier** [comment]
Thank you for your response! I was now able to install DRAM and can't wait to start using it!


Best,
Emma Boismier
________________________________

**Comment by rmFlynn** [comment]
This functionality will be on the way in DRAM2
