### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by ayixon** [WrightonLabCSU/DRAM#75]
Hello develloper, i am getting the following error with dram.py annotate. I verified all my database and looks ok. Any idea about this:  AttributeError: 'NoneType' object has no attribute 'split'
-----------------------------------------------------------------------------------------
DRAM.py annotate -i my_bins/bin_23.fasta -o annotation
1 fastas found
2021-04-11 21:40:30.752591: Annotation started
0:00:00.322053: Retrieved database locations and descriptions
0:00:00.322901: Annotating bin_23
0:00:01.987539: Turning genes from prodigal to mmseqs2 db
0:00:12.517293: Getting hits from kofam
0:03:03.557675: Getting forward best hits from peptidase
0:03:11.091172: Getting reverse best hits from peptidase
0:03:13.247625: Getting descriptions of hits from peptidase
0:03:13.259300: Getting hits from pfam
0:03:55.862241: Getting hits from dbCAN
0:03:58.053379: Getting hits from VOGDB
/home/user/miniconda3/lib/python3.9/site-packages/mag_annotator/database_handler.py:42: UserWarning: No descriptions were found for your id's. Does this VOG23534 look like an id from vogdb_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
Traceback (most recent call last):
  File "/home/user/miniconda3/bin/DRAM.py", line 153, in <module>
    args.func(**args_dict)
  File "/home/user/miniconda3/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 967, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/home/user/miniconda3/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1005, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, prodigal_mode,
  File "/home/user/miniconda3/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 923, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/home/user/miniconda3/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 824, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/home/user/miniconda3/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 778, in annotate_orfs
    annotation_list.append(run_hmmscan_vogdb(gene_faa, db_locs['vogdb'], tmp_dir, threads, db_handler=db_handler,
  File "/home/user/miniconda3/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 343, in run_hmmscan_vogdb
    categories_str = description.split('; ')[-1]
AttributeError: 'NoneType' object has no attribute 'split'
-------------------------------------------------------------------------------------------------------

**Comment by ayixon** [comment]
I partially solved the problem by giving "null" attribute to the VOGDB db in the config file.
The rest of the pipeline ran without major problems.
I guess this "solution" doesn't affect me because I'm not interested in viral information ... i am right? 

best
ayixon

**Comment by shafferm** [comment]
Can you check if you can find `VOG23534` in the vog_annotations.tsv.gz file? You should be able to see where it is by running `DRAM-setup.py print_config`. But in the end if you don't care about viral annotations your fix will work. We are working on making the databases used during annotation more customizable now.

**Comment by rmFlynn** [comment]
Closing from inactivity
