### ISSUE TITLE
DRAM-v : Extraction of flag information for manual annotation?

### ISSUE THREAD

**Issue by ChenTianYi99** [WrightonLabCSU/DRAM#87]
Hi, 
I have obtained multiple viral sequences identified by several tools. Now I want to annotate AMGs manually based on KEGG database. According to DRAM-v, several flags are designated to viral contigs. So if it is possible to extract these flags so that i could filter positive-false AMGs manually? (which database file contains these flags information)

Thanks.

**Comment by rmFlynn** [comment]
Good reading for those that are interested in DRAM-v, makes me inspired to put the supplemental material more prominently in the read me.
